;
; ============================================
; File     : tools/disasm/x86.s
; Project  : utasm
; Author   : Utkarsha Lab
; License  : Apache-2.0
; ============================================
;

%include "include/constant.inc"
%include "include/type.inc"
%include "include/macro.inc"

DEFAULT REL

; ============================================================================
; X86-64 INSTRUCTION DECODER
; ============================================================================
; Decodes one instruction and writes it in Intel syntax, in the same style
; as `objdump -d -M intel`, so the two can be compared line by line:
;
;     x86_decode(code, available, address, fmtbuf) -> length, branch target
;
; Coverage (stage 1): legacy prefixes, REX, the one-byte map and the 0F map
; for general-purpose instructions (ALU, mov/lea/xchg, push/pop, shifts,
; mul/div, inc/dec/not/neg, test/cmp, jumps/calls/ret, setcc/cmovcc/jcc,
; movzx/movsx/movsxd, bt*, bsf/bsr, shld/shrd, cmpxchg/xadd, bswap,
; string instructions with rep, nop forms, syscall, cpuid, rdtsc, ...).
; Everything else - SSE/AVX, 0F 38 / 0F 3A, x87 - decodes as "(bad)"
; (length 0) for now.
;
; The opcode tables are generated by scripts/gen_x86_tables.py into
; x86_tables.inc; the FM_* / FL_* numbers below must match that script.
;
; Calling convention (AMD64):
;   args  : rdi, rsi, rdx, rcx
;   callee saved: rbx, rbp, r12-r15

; ---- operand forms (FORMS in scripts/gen_x86_tables.py) ----
%define FM_NONE      0
%define FM_EbGb      1
%define FM_EvGv      2
%define FM_GbEb      3
%define FM_GvEv      4
%define FM_ALIb      5
%define FM_eAXIz     6
%define FM_Zv        7
%define FM_ZbIb      8
%define FM_ZvIv      9
%define FM_Jb       10
%define FM_Jz       11
%define FM_Eb       12
%define FM_Ev       13
%define FM_EbIb     14
%define FM_EvIz     15
%define FM_EvIb     16
%define FM_Eb1      17
%define FM_Ev1      18
%define FM_EbCL     19
%define FM_EvCL     20
%define FM_EbIbU    21
%define FM_EvIbU    22
%define FM_GvM      23
%define FM_GvEvIz   24
%define FM_GvEvIb   25
%define FM_GvEb     26
%define FM_GvEw     27
%define FM_GvEd     28
%define FM_IbU      29
%define FM_IbS      30
%define FM_Iz       31
%define FM_Iw       32
%define FM_ZvXchg   33
%define FM_EvGv_bt  34
%define FM_EvGvIb   35
%define FM_EvGvCL   36
%define FM_STR      37
%define FM_XCHG90   38
%define FM_CBW      39
%define FM_CWD      40
%define FM_Ewv      41          ; sldt/str/...: register at operand size, memory WORD
%define FM_G7       42          ; 0F 01: system instructions (sgdt, rdtscp, ...)
%define FM_GAE      43          ; 0F AE: fences, fxsave, ldmxcsr, clflush, ...
; SSE-family forms (V = xmm/mm from ModRM.reg, W = xmm/mm or memory from
; ModRM.rm, U = register-only rm, M = memory-only rm, E/G = general register)
%define FM_VW       44
%define FM_WV       45
%define FM_VWI      46
%define FM_VE       47
%define FM_EV       48
%define FM_GW       49
%define FM_GU       50
%define FM_UI       51          ; shift-by-immediate group (0F 71/72/73)
%define FM_VM       52
%define FM_MV       53
%define FM_V12      54          ; movlps/movhps (memory) or movhlps/movlhps
%define FM_EVI      55
%define FM_VEI      56
%define FM_GUI      57
%define FM_VW0      58          ; blendv*: implicit xmm0 third operand
%define FM_CMPS     59          ; cmpps & co: imm < 8 becomes cmpltps & co
%define FM_PCLMUL   60
%define FM_ENDBR    61
; VEX-only forms (x86_vex0f / x86_vex38 / x86_vex3a)
%define FM_XBCAST   62          ; broadcast: V (xmm/ymm by L), xmm or memory
%define FM_XINS     63          ; vinsert*128: ymm, ymm, xmm/m128, imm8
%define FM_XEXT     64          ; vextract*128: xmm/m128, ymm, imm8
%define FM_XIS4     65          ; vblendv*: V, vvvv, W, register in imm8[7:4]
%define FM_BGBE     66          ; BMI: gpr, vvvv gpr, r/m
%define FM_BGEB     67          ; BMI: gpr, r/m, vvvv gpr
%define FM_BBE      68          ; BMI group: vvvv gpr, r/m
%define FM_XMLD     69          ; masked load: V, vvvv, mem
%define FM_XMST     70          ; masked store: mem, vvvv, V
%define FM_BRORX    71          ; rorx: gpr, r/m, imm8
%define FM_XZERO    72          ; vzeroupper / vzeroall
%define FM_X87      73          ; x87 escape (D8-DF), decoded by dx_x87
%define FM_EVEX     74          ; EVEX (AVX-512), operands by dx_evex_operands
%define FM_G9       75          ; 0F C7: cmpxchg8b/16b, rdrand, rdseed

; ---- EVEX entry flags (EV_* in scripts/gen_x86_tables.py) ----
%define EV_BCST     1           ; EVEX.b with memory: broadcast one element
%define EV_SCALAR   2           ; V and H are xmm whatever the vector length
%define EV_ER       4           ; EVEX.b with registers: rounding control
%define EV_SAE      8           ; EVEX.b with registers: {sae}
%define EV_PINT     16          ; vpcmp predicate in the name
%define EV_PFP      32          ; vcmp predicate in the name
%define EV_NELEM    64          ; disp8*N scales by one element
%define EV_MOVS     128         ; vmovss/vmovsd: H only in the register form

; SSE entry flags (x86_sse0f / x86_sse38 / x86_sse3a)
%define SF_MEM      7           ; memory size: 1 B, 2 W, 3 D, 4 Q, 5 vector
%define SF_MMX      8           ; mm registers
%define SF_WQ       16          ; REX.W: trailing 'd' of the name becomes 'q'
%define SF_NDS      32          ; VEX: extra source register
%define SF_NOVEX    64
%define SF_INT      0x80        ; an integer instruction: flags are FL_*
%define VF_WSD      8           ; VEX-only tables: VEX.W turns the last 's' into 'd'

; ---- entry flags ----
%define FL_MODRM     1
%define FL_GROUP     2
%define FL_BYTE      4
%define FL_D64       8          ; default 64-bit operand size (push/pop)
%define FL_F64      16          ; always 64-bit (near call/jmp)

%define NO_REG      0xFF
%define RIP_REG     0xFE

extern fmt_str
extern fmt_char
extern fmt_hex
extern fmt_pad
extern fmt_udec

[SECTION .bss]
align 8
dx_start:   resq 1              ; first byte of the instruction
dx_cur:     resq 1              ; next byte to read
dx_end:     resq 1              ; end of readable bytes (at most 15 on)
dx_addr:    resq 1              ; address of the instruction
dx_fb:      resq 1              ; FmtBuf being written
dx_target:  resq 1              ; direct branch target, or -1
dx_mnem:    resq 1              ; mnemonic string
dx_disp:    resq 1              ; memory displacement (sign-extended)
dx_textpos: resq 1              ; FmtBuf length where this text began
dx_rex:     resb 1              ; REX byte, or 0
dx_p66:     resb 1
dx_n66:     resb 1              ; number of 66 prefixes (extra ones print data16)
dx_sflags:  resb 1              ; SSE entry flags, 0 for integer instructions
dx_vex:     resb 1              ; 1 = VEX-encoded
dx_vl:      resb 1              ; VEX.L
dx_vvvv:    resb 1              ; VEX.vvvv (already inverted), 0-15
dx_vpfx:    resb 1              ; print a "v" before the SSE name
dx_vclass:  resb 1              ; vector registers: 0 mm, 1 xmm, 2 ymm
dx_half:    resb 1              ; widening op: source is half the destination width
dx_narrow:  resb 1              ; narrowing op: xmm destination, source by VEX.L
dx_namebuf: resb 24             ; a mnemonic built at decode time
dx_p67:     resb 1              ; address-size prefix: 32-bit address registers
dx_map:     resb 1              ; 1 = one-byte map, 2 = 0F map
dx_lock:    resb 1
dx_rep:     resb 1              ; F3
dx_repne:   resb 1              ; F2
dx_seg:     resb 1              ; segment override letter (c,s,d,e,f,g) or 0
dx_fail:    resb 1              ; ran out of bytes / invalid
dx_op:      resb 1              ; opcode byte
dx_form:    resb 1
dx_flags:   resb 1
dx_osz:     resb 1              ; operand size in bits: 8, 16, 32, 64
dx_mod:     resb 1
dx_modrm:   resb 1              ; the raw ModRM byte
dx_regno:   resb 1              ; ModRM.reg with REX.R (0-15)
dx_rmreg:   resb 1              ; ModRM.rm register with REX.B (mod == 3)
dx_base:    resb 1              ; 0-15, NO_REG or RIP_REG
dx_index:   resb 1              ; 0-15 or NO_REG
dx_scale:   resb 1
dx_hasdisp: resb 1
dx_disp8n:  resb 1              ; disp8 scale (EVEX disp8*N), else 1
dx_evex:    resb 1              ; 1 = EVEX-encoded
dx_reghi:   resb 1              ; 16 when EVEX.R' selects vector registers 16-31
dx_rmhi:    resb 1              ; 16 when EVEX.X does (register ModRM.rm)
dx_eaaa:    resb 1              ; EVEX opmask register (0 = none)
dx_ez:      resb 1              ; EVEX.z: zeroing
dx_eb:      resb 1              ; EVEX.b: broadcast / rounding / sae
dx_eround:  resb 1              ; rounding mode (EVEX.L'L with b and registers)
dx_emsize:  resb 1              ; entry memory size class
dx_eflags:  resb 1              ; entry EV_* flags
dx_epred:   resb 1              ; the imm8 is a predicate already in the name
dx_fwait:   resb 1              ; 9B folded into the x87 instruction (fstsw ...)

[SECTION .text]

; ---- x86_decode --------------------------
;
; x86_decode
; Decodes the instruction at rdi and appends its text to a FmtBuf.
; Input    : rdi = pointer to the code
;            rsi = bytes available from rdi
;            rdx = the instruction's address (for branch targets)
;            rcx = FmtBuf to append to
; Output   : rax = instruction length, or 0 if it could not be decoded
;              (nothing useful is written then; print "(bad)")
;            rdx = target address of a direct jmp/jcc/call/loop, or -1
;
global x86_decode
x86_decode:
    push    rbx
    push    r12
    push    r13
    push    r14
    push    r15

    mov     [rel dx_start], rdi
    mov     [rel dx_cur], rdi
    cmp     rsi, 15
    jbe     .avail_ok
    mov     esi, 15                        ; an instruction is at most 15 bytes
.avail_ok:
    add     rsi, rdi
    mov     [rel dx_end], rsi
    mov     [rel dx_addr], rdx
    mov     [rel dx_fb], rcx
    mov     rax, [rcx + FMTBUF_len]
    mov     [rel dx_textpos], rax
    mov     qword [rel dx_target], -1
    xor     eax, eax
    mov     [rel dx_rex], al
    mov     [rel dx_p66], al
    mov     [rel dx_n66], al
    mov     [rel dx_sflags], al
    mov     [rel dx_vex], al
    mov     [rel dx_vl], al
    mov     [rel dx_vvvv], al
    mov     [rel dx_vpfx], al
    mov     [rel dx_half], al
    mov     [rel dx_narrow], al
    mov     byte [rel dx_vclass], 1
    mov     [rel dx_p67], al
    mov     [rel dx_lock], al
    mov     [rel dx_rep], al
    mov     [rel dx_repne], al
    mov     [rel dx_seg], al
    mov     [rel dx_fail], al
    mov     [rel dx_evex], al
    mov     [rel dx_reghi], al
    mov     [rel dx_rmhi], al
    mov     [rel dx_eaaa], al
    mov     [rel dx_ez], al
    mov     [rel dx_eb], al
    mov     [rel dx_epred], al
    mov     [rel dx_fwait], al
    mov     byte [rel dx_disp8n], 1

    ; ---- legacy prefixes ----
.prefix:
    call    dx_peek
    cmp     byte [rel dx_fail], 0
    jne     .bad
    cmp     al, 0xF0
    je      .p_lock
    cmp     al, 0xF2
    je      .p_repne
    cmp     al, 0xF3
    je      .p_rep
    cmp     al, 0x66
    je      .p_66
    cmp     al, 0x67
    je      .p_67
    mov     cl, 'c'
    cmp     al, 0x2E
    je      .p_seg
    mov     cl, 's'
    cmp     al, 0x36
    je      .p_seg
    mov     cl, 'd'
    cmp     al, 0x3E
    je      .p_seg
    mov     cl, 'e'
    cmp     al, 0x26
    je      .p_seg
    mov     cl, 'f'
    cmp     al, 0x64
    je      .p_seg
    mov     cl, 'g'
    cmp     al, 0x65
    je      .p_seg
    jmp     .rex
.p_lock:
    mov     byte [rel dx_lock], 1
    jmp     .p_skip
.p_repne:
    mov     byte [rel dx_repne], 1
    jmp     .p_skip
.p_rep:
    mov     byte [rel dx_rep], 1
    jmp     .p_skip
.p_66:
    mov     byte [rel dx_p66], 1
    inc     byte [rel dx_n66]
    jmp     .p_skip
.p_67:
    mov     byte [rel dx_p67], 1
    jmp     .p_skip
.p_seg:
    mov     [rel dx_seg], cl
.p_skip:
    call    dx_rd8
    jmp     .prefix

    ; ---- REX ----
.rex:
    cmp     al, 0x62
    je      .evex
    cmp     al, 0xC5
    je      .vex2
    cmp     al, 0xC4
    je      .vex3
    mov     ecx, eax
    and     ecx, 0xF0
    cmp     ecx, 0x40
    jne     .opcode
    call    dx_rd8
    mov     [rel dx_rex], al
    jmp     .opcode

    ; ---- VEX (C5 xx / C4 xx xx): AVX, AVX2, FMA, BMI ----
; The R/X/B/W bits become a synthetic REX byte, so the ModRM/SIB code and
; the REX.W checks work unchanged. R, X, B and vvvv are stored inverted.
.vex2:
    call    dx_rd8                         ; C5
    call    dx_rd8                         ; R vvvv L pp
    mov     byte [rel dx_map], 2           ; implied 0F map
    mov     edx, 0x40
    test    al, 0x80
    jnz     .vex_fields
    or      edx, 4                         ; R
    jmp     .vex_fields
.vex3:
    call    dx_rd8                         ; C4
    call    dx_rd8                         ; R X B mmmmm
    mov     edx, 0x40
    test    al, 0x80
    jnz     .v3_x
    or      edx, 4                         ; R
.v3_x:
    test    al, 0x40
    jnz     .v3_b
    or      edx, 2                         ; X
.v3_b:
    test    al, 0x20
    jnz     .v3_map
    or      edx, 1                         ; B
.v3_map:
    and     eax, 0x1F
    cmp     eax, 1
    jb      .bad
    cmp     eax, 3
    ja      .bad
    inc     eax                            ; 1/2/3 -> maps 2/3/4 (0F, 0F38, 0F3A)
    mov     [rel dx_map], al
    call    dx_rd8                         ; W vvvv L pp (rd8 keeps edx)
    test    al, 0x80
    jz      .vex_fields
    or      edx, 8                         ; W
.vex_fields:
    ; eax = the byte holding vvvv L pp, edx = synthetic REX
    mov     [rel dx_rex], dl
    mov     ecx, eax
    shr     ecx, 3
    not     ecx
    and     ecx, 15
    mov     [rel dx_vvvv], cl
    mov     ecx, eax
    shr     ecx, 2
    and     ecx, 1
    mov     [rel dx_vl], cl
    and     eax, 3                         ; pp: prefix index
    mov     byte [rel dx_vex], 1
    push    rax
    call    dx_rd8                         ; opcode
    mov     [rel dx_op], al
    pop     rcx
    cmp     byte [rel dx_fail], 0
    jne     .bad
    ; k-mask instructions (AVX-512 opmask registers)
    call    dx_kop_find                    ; keeps rcx
    test    rax, rax
    jnz     .kop
    cmp     byte [rel dx_map], 2
    jne     .vex_tables
    cmp     byte [rel dx_op], 0xAE
    jne     .vex_tables
    test    ecx, ecx
    jz      .vex_ae
    jmp     .bad
.vex_tables:
    ; VEX-only table first
    lea     rdx, [rel x86_vex0f]
    cmp     byte [rel dx_map], 3
    jb      .vex_tab
    lea     rdx, [rel x86_vex38]
    je      .vex_tab
    lea     rdx, [rel x86_vex3a]
.vex_tab:
    movzx   eax, byte [rel dx_op]
    lea     eax, [rax*4 + rcx]
    lea     r12, [rdx + rax*4]
    movzx   r13d, word [r12]
    cmp     r13d, 0xFFFF
    je      .vex_sse
    mov     al, [r12 + 3]
    mov     [rel dx_sflags], al            ; bit 3 = VF_WSD here
    jmp     .vex_loaded
.vex_sse:
    ; otherwise the SSE instruction with a "v" in front
    lea     rdx, [rel x86_sse0f]
    cmp     byte [rel dx_map], 3
    jb      .vex_sse_tab
    lea     rdx, [rel x86_sse38]
    je      .vex_sse_tab
    lea     rdx, [rel x86_sse3a]
.vex_sse_tab:
    movzx   eax, byte [rel dx_op]
    lea     eax, [rax*4 + rcx]
    lea     r12, [rdx + rax*4]
    movzx   r13d, word [r12]
    cmp     r13d, 0xFFFF
    je      .bad
    mov     al, [r12 + 3]
    test    al, SF_INT | SF_NOVEX | SF_MMX
    jnz     .bad
    mov     [rel dx_sflags], al
    mov     byte [rel dx_vpfx], 1
.vex_loaded:
    or      byte [rel dx_sflags], 0x80     ; mark "vector"
    mov     al, [r12 + 2]
    mov     [rel dx_form], al
    mov     byte [rel dx_flags], FL_MODRM
    cmp     al, FM_XZERO
    jne     .vex_class
    mov     byte [rel dx_flags], 0
.vex_class:
    ; xmm, or ymm with VEX.L for packed operations (scalar ones stay xmm)
    mov     byte [rel dx_vclass], 1
    ; widening moves/conversions: xmm/ymm destination, half-width source
    cmp     byte [rel dx_map], 3
    jne     .half_0f
    movzx   eax, byte [rel dx_op]
    and     eax, 0xEF                      ; 20-25 and 30-35
    cmp     eax, 0x20
    jb      .not_half
    cmp     eax, 0x25
    ja      .not_half
    jmp     .is_half
.half_0f:
    cmp     byte [rel dx_map], 2
    jne     .not_half
    cmp     byte [rel dx_op], 0x5A         ; vcvtps2pd (no prefix)
    jne     .half_e6
    cmp     byte [rel dx_vpfx], 0
    je      .not_half
    cmp     ecx, 0
    je      .is_half
    cmp     ecx, 1                         ; vcvtpd2ps (66)
    je      .is_narrow
    jmp     .not_half
.half_e6:
    cmp     byte [rel dx_op], 0xE6         ; vcvtdq2pd (F3)
    jne     .not_half
    cmp     ecx, 2
    je      .is_half
    jmp     .is_narrow                     ; vcvttpd2dq (66), vcvtpd2dq (F2)
.is_narrow:
    mov     byte [rel dx_narrow], 1
    jmp     .not_half
.is_half:
    mov     byte [rel dx_half], 1
    jmp     .by_l
.not_half:
    cmp     byte [rel dx_form], FM_XBCAST
    je      .by_l                          ; broadcasts: destination by VEX.L
    cmp     byte [rel dx_vl], 0
    je      .entry_loaded
    movzx   eax, byte [rel dx_sflags]
    and     eax, SF_MEM
    jz      .vex_ymm
    cmp     eax, 5
    jne     .entry_loaded
.vex_ymm:
    mov     byte [rel dx_vclass], 2
    jmp     .entry_loaded
.by_l:
    cmp     byte [rel dx_vl], 0
    je      .entry_loaded
    mov     byte [rel dx_vclass], 2
    jmp     .entry_loaded

    ; ---- EVEX (62 P0 P1 P2): AVX-512 ----
; P0 = R X B R' 0 0 m m, P1 = W vvvv 1 pp, P2 = z L'L b V' aaa. As with VEX,
; R/X/B/W become a synthetic REX byte; R' (and X for a register rm) select
; vector registers 16-31, V' extends vvvv.
.evex:
    call    dx_rd8                         ; 62
    call    dx_rd8                         ; P0
    test    al, 0x0C
    jnz     .bad
    mov     ecx, eax
    and     ecx, 3
    jz      .bad
    inc     ecx                            ; 1/2/3 -> maps 2/3/4
    mov     [rel dx_map], cl
    mov     edx, 0x40
    test    al, 0x80
    jnz     .e_x
    or      edx, 4                         ; R
.e_x:
    test    al, 0x40
    jnz     .e_b
    or      edx, 2                         ; X
    mov     byte [rel dx_rmhi], 16
.e_b:
    test    al, 0x20
    jnz     .e_r2
    or      edx, 1                         ; B
.e_r2:
    test    al, 0x10
    jnz     .e_p1
    mov     byte [rel dx_reghi], 16        ; R'
.e_p1:
    call    dx_rd8                         ; P1 (rd8 keeps edx)
    test    al, 4
    jz      .bad
    test    al, 0x80
    jz      .e_w
    or      edx, 8                         ; W
.e_w:
    mov     [rel dx_rex], dl
    mov     ecx, eax
    shr     ecx, 3
    not     ecx
    and     ecx, 15
    mov     [rel dx_vvvv], cl
    and     eax, 3
    mov     r8d, eax                       ; pp
    call    dx_rd8                         ; P2
    mov     ecx, eax
    and     ecx, 7
    mov     [rel dx_eaaa], cl
    mov     ecx, eax
    shr     ecx, 7
    mov     [rel dx_ez], cl
    mov     ecx, eax
    shr     ecx, 4
    and     ecx, 1
    mov     [rel dx_eb], cl
    mov     ecx, eax
    shr     ecx, 5
    and     ecx, 3
    mov     [rel dx_vl], cl
    test    al, 8
    jnz     .e_op
    or      byte [rel dx_vvvv], 16         ; V'
.e_op:
    call    dx_rd8                         ; opcode
    mov     [rel dx_op], al
    cmp     byte [rel dx_fail], 0
    jne     .bad
    ; key = map << 24 | opcode << 16 | pp << 8 | W << 4
    movzx   ecx, byte [rel dx_map]
    shl     ecx, 8
    or      ecx, eax
    shl     ecx, 8
    or      ecx, r8d
    shl     ecx, 8
    test    byte [rel dx_rex], 8
    jz      .e_key
    or      ecx, 0x10
.e_key:
    mov     r9d, ecx
    call    dx_evex_find
    test    r12, r12
    jnz     .e_found
    ; a group member: 8 + ModRM.reg in the key
    call    dx_peek
    cmp     byte [rel dx_fail], 0
    jne     .bad
    shr     eax, 3
    and     eax, 7
    lea     ecx, [r9 + rax + 8]
    call    dx_evex_find
    test    r12, r12
    jz      .bad
.e_found:
    mov     byte [rel dx_evex], 1
    movzx   r13d, word [r12 + 4]           ; name
    mov     al, [r12 + 6]
    mov     [rel dx_emsize], al
    mov     al, [r12 + 7]
    mov     [rel dx_eflags], al
    call    dx_peek                        ; ModRM
    cmp     byte [rel dx_fail], 0
    jne     .bad
    shr     eax, 6
    cmp     eax, 3
    je      .e_regs
    ; memory: EVEX.b broadcasts one element, and disp8 is scaled by N
    cmp     byte [rel dx_vl], 3
    je      .bad
    cmp     byte [rel dx_eb], 0
    je      .e_n_size
    test    byte [rel dx_eflags], EV_BCST
    jz      .bad
    jmp     .e_n_elem
.e_n_size:
    test    byte [rel dx_eflags], EV_NELEM
    jnz     .e_n_elem
    call    dx_evex_bytes
    jmp     .e_n
.e_n_elem:
    call    dx_evex_elem
.e_n:
    mov     [rel dx_disp8n], al
    jmp     .e_ready
.e_regs:
    ; registers: EVEX.b means rounding control or {sae}, at 512 bits
    cmp     byte [rel dx_eb], 0
    je      .e_len
    test    byte [rel dx_eflags], EV_ER | EV_SAE
    jz      .bad
    mov     al, [rel dx_vl]
    mov     [rel dx_eround], al
    mov     byte [rel dx_vl], 2
    jmp     .e_ready
.e_len:
    cmp     byte [rel dx_vl], 3
    je      .bad
.e_ready:
    mov     byte [rel dx_flags], FL_MODRM
    mov     byte [rel dx_form], FM_EVEX
    jmp     .entry_loaded

    ; ---- opcode ----
.opcode:
    call    dx_rd8
    cmp     byte [rel dx_fail], 0
    jne     .bad
    lea     r12, [rel x86_map1]
    mov     byte [rel dx_map], 1
    cmp     al, 0x0F
    jne     .have_op
    mov     byte [rel dx_map], 2
    call    dx_rd8
    cmp     byte [rel dx_fail], 0
    jne     .bad
    cmp     al, 0x38
    je      .map38
    cmp     al, 0x3A
    je      .map3a
    lea     r12, [rel x86_map2]
    jmp     .have_op
.map38:
    mov     byte [rel dx_map], 3
    jmp     .map3
.map3a:
    mov     byte [rel dx_map], 4
.map3:
    call    dx_rd8                         ; the opcode byte after 0F 38 / 0F 3A
    cmp     byte [rel dx_fail], 0
    jne     .bad
.have_op:
    mov     [rel dx_op], al
    ; 9B + fnstsw/fnstcw/fnclex/...: objdump writes one instruction, no "n"
    cmp     byte [rel dx_map], 1
    jne     .not_wait
    cmp     al, 0x9B
    jne     .not_wait
    call    dx_fwait_combo
    test    eax, eax
    jz      .not_wait
    call    dx_rd8
    mov     [rel dx_op], al
    mov     byte [rel dx_fwait], 1
    jmp     .x87
.not_wait:

    ; ---- SSE family: 0F / 0F 38 / 0F 3A chosen by the mandatory prefix ----
    cmp     byte [rel dx_map], 2
    jb      .integer
    xor     ecx, ecx                       ; prefix index: none
    cmp     byte [rel dx_p66], 0
    je      .pfx_f3
    mov     ecx, 1                         ; 66
.pfx_f3:
    cmp     byte [rel dx_rep], 0
    je      .pfx_f2
    mov     ecx, 2                         ; F3
.pfx_f2:
    cmp     byte [rel dx_repne], 0
    je      .pfx_done
    mov     ecx, 3                         ; F2
.pfx_done:
    lea     rdx, [rel x86_sse0f]
    cmp     byte [rel dx_map], 3
    jb      .sse_tab
    lea     rdx, [rel x86_sse38]
    je      .sse_tab
    lea     rdx, [rel x86_sse3a]
.sse_tab:
    movzx   eax, byte [rel dx_op]
    lea     eax, [rax*4 + rcx]
    lea     rdx, [rdx + rax*4]
    movzx   eax, word [rdx]
    cmp     eax, 0xFFFF
    je      .sse_none
    mov     r12, rdx
    mov     r13d, eax
    ; the prefix is part of the opcode now, not operand size / rep
    cmp     ecx, 1
    jne     .sse_c2
    mov     byte [rel dx_p66], 0
    dec     byte [rel dx_n66]
.sse_c2:
    cmp     ecx, 2
    jne     .sse_c3
    mov     byte [rel dx_rep], 0
.sse_c3:
    cmp     ecx, 3
    jne     .sse_c4
    mov     byte [rel dx_repne], 0
.sse_c4:
    mov     al, [r12 + 2]
    mov     [rel dx_form], al
    mov     al, [r12 + 3]
    test    al, SF_INT
    jz      .sse_vec
    and     al, 0x7F                       ; integer instruction: FL_* flags
    mov     [rel dx_flags], al
    jmp     .entry_loaded
.sse_vec:
    mov     [rel dx_sflags], al
    or      byte [rel dx_sflags], 0x80     ; mark "SSE" even with no flags set
    test    al, SF_MMX
    jz      .sse_xmm
    mov     byte [rel dx_vclass], 0
.sse_xmm:
    mov     byte [rel dx_flags], FL_MODRM
    cmp     byte [rel dx_form], FM_NONE
    jne     .entry_loaded
    mov     byte [rel dx_flags], 0         ; emms: no ModRM
    jmp     .entry_loaded
.sse_none:
    cmp     byte [rel dx_map], 2
    jne     .bad                           ; nothing else in 0F 38 / 0F 3A
    lea     r12, [rel x86_map2]
.integer:
    movzx   eax, byte [rel dx_op]
    lea     r12, [r12 + rax*4]             ; r12 = table entry
    movzx   r13d, word [r12]               ; r13 = name offset / group
    cmp     r13d, 0xFFFF
    je      .bad
    mov     al, [r12 + 2]
    mov     [rel dx_form], al
    cmp     al, FM_X87
    je      .x87
    mov     al, [r12 + 3]
    mov     [rel dx_flags], al
.entry_loaded:

    ; ---- ModRM (and SIB / displacement) ----
    test    byte [rel dx_flags], FL_MODRM
    jz      .no_modrm
    call    dx_modrm_decode
    cmp     byte [rel dx_fail], 0
    jne     .bad
.no_modrm:

    ; ---- groups: the mnemonic comes from ModRM.reg ----
    test    byte [rel dx_flags], FL_GROUP
    jz      .named
    lea     rax, [rel x86_groups]
    shl     r13d, 3                        ; group * 8
    movzx   ecx, byte [rel dx_regno]
    and     ecx, 7
    add     r13d, ecx
    lea     r12, [rax + r13*4]             ; group entry
    movzx   r13d, word [r12]
    cmp     r13d, 0xFFFF
    je      .bad
    mov     al, [r12 + 2]
    test    al, al
    jz      .keep_form
    mov     [rel dx_form], al
.keep_form:
    mov     al, [r12 + 3]
    or      [rel dx_flags], al
.named:
    lea     rax, [rel x86_names]
    add     rax, r13
    mov     [rel dx_mnem], rax

    ; ---- operand size ----
    mov     al, 8
    test    byte [rel dx_flags], FL_BYTE
    jnz     .osz
    mov     al, 64
    test    byte [rel dx_rex], 8           ; REX.W
    jnz     .osz
    test    byte [rel dx_flags], FL_F64
    jnz     .osz
    test    byte [rel dx_flags], FL_D64
    jz      .osz_std
    cmp     byte [rel dx_p66], 0
    je      .osz
    mov     al, 16
    jmp     .osz
.osz_std:
    mov     al, 32
    cmp     byte [rel dx_p66], 0
    je      .osz
    mov     al, 16
.osz:
    mov     [rel dx_osz], al

    ; ---- redundant 66 prefixes: objdump writes "data16 " for each ----
.data16:
    movzx   eax, byte [rel dx_n66]
    test    eax, eax
    jz      .rexw
    test    byte [rel dx_rex], 8
    jz      .d16_keep
    cmp     byte [rel dx_sflags], 0
    je      .d16_loop                      ; REX.W overrides 66: each is data16
.d16_keep:
    dec     eax                            ; one 66 sets the operand size
.d16_loop:
    test    eax, eax
    jz      .rexw
    push    rax
    lea     rsi, [rel s_data16]
    call    dx_puts
    pop     rax
    dec     eax
    jmp     .d16_loop
    ; ---- REX.W on a near call/jmp does nothing: objdump writes "rex.W" ----
.rexw:
    test    byte [rel dx_rex], 8
    jz      .data16_done
    test    byte [rel dx_flags], FL_F64
    jz      .data16_done
    cmp     byte [rel dx_sflags], 0
    jne     .data16_done
    lea     rsi, [rel s_rexw]
    call    dx_puts
.data16_done:

    ; ---- one-byte map prefixes objdump spells out ----
    cmp     byte [rel dx_map], 1
    jne     .spelled_done
    ; F3 C3 / F3 C2: "repz ret"
    movzx   eax, byte [rel dx_op]
    and     eax, 0xFE
    cmp     eax, 0xC2
    jne     .notrack
    cmp     byte [rel dx_rep], 0
    je      .spelled_done
    mov     byte [rel dx_rep], 0
    lea     rsi, [rel s_repz]
    call    dx_puts
    jmp     .spelled_done
.notrack:
    ; 3E on an indirect call/jmp (FF /2, FF /4): "notrack"
    cmp     byte [rel dx_op], 0xFF
    jne     .spelled_done
    cmp     byte [rel dx_seg], 'd'
    jne     .spelled_done
    movzx   eax, byte [rel dx_regno]
    and     eax, 7
    cmp     eax, 2
    je      .notrack_put
    cmp     eax, 4
    jne     .spelled_done
.notrack_put:
    mov     byte [rel dx_seg], 0
    lea     rsi, [rel s_notrack]
    call    dx_puts
.spelled_done:

    ; ---- 0F 1F nop with a segment prefix: objdump writes "cs nop ..." ----
    cmp     byte [rel dx_map], 2
    jne     .operands
    cmp     byte [rel dx_op], 0x1F
    jne     .operands
    movzx   esi, byte [rel dx_seg]
    test    esi, esi
    jz      .operands
    mov     byte [rel dx_seg], 0
    call    dx_putc                        ; 'c' (etc.) + "s "
    mov     esi, 's'
    call    dx_putc
    mov     esi, ' '
    call    dx_putc

    ; ---- operands ----
.operands:
    call    dx_operands
    cmp     byte [rel dx_fail], 0
    jne     .bad
    jmp     .finish

    ; ---- x87 floating point: ModRM, then its own tables ----
.x87:
    call    dx_modrm_decode
    cmp     byte [rel dx_fail], 0
    jne     .bad
    call    dx_x87
    cmp     byte [rel dx_fail], 0
    jne     .bad
    jmp     .finish

    ; ---- k-mask instructions: rax = x86_kops entry ----
.kop:
    mov     r12, rax
    call    dx_modrm_decode
    cmp     byte [rel dx_fail], 0
    jne     .bad
    call    dx_kop
    cmp     byte [rel dx_fail], 0
    jne     .bad
    jmp     .finish

    ; ---- VEX 0F AE: vldmxcsr / vstmxcsr (memory, /2 and /3) ----
.vex_ae:
    cmp     byte [rel dx_vl], 0
    jne     .bad
    call    dx_modrm_decode
    cmp     byte [rel dx_fail], 0
    jne     .bad
    cmp     byte [rel dx_mod], 3
    je      .bad
    movzx   eax, byte [rel dx_regno]
    and     eax, 7
    lea     rsi, [rel s_vldmxcsr]
    cmp     eax, 2
    je      .vex_ae_put
    lea     rsi, [rel s_vstmxcsr]
    cmp     eax, 3
    jne     .bad
.vex_ae_put:
    mov     [rel dx_mnem], rsi
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, 32
    call    dx_mem
    cmp     byte [rel dx_fail], 0
    jne     .bad

.finish:
    mov     rax, [rel dx_cur]
    sub     rax, [rel dx_start]            ; length
    mov     rdx, [rel dx_target]
    jmp     .ret

.bad:
    ; undo any partial text
    mov     rcx, [rel dx_fb]
    mov     rax, [rel dx_textpos]
    mov     [rcx + FMTBUF_len], rax
    mov     rdx, [rcx + FMTBUF_buf]
    mov     byte [rdx + rax], 0
    xor     eax, eax
    mov     rdx, -1
.ret:
    pop     r15
    pop     r14
    pop     r13
    pop     r12
    pop     rbx
    ret

; ============================================================================
; Byte reading
; ============================================================================

; dx_peek: al = next byte without consuming it (sets dx_fail at the end)
dx_peek:
    mov     rcx, [rel dx_cur]
    cmp     rcx, [rel dx_end]
    jae     dx_rd_fail
    movzx   eax, byte [rcx]
    ret

; dx_rd8: eax = next byte (zero-extended), consumed
dx_rd8:
    mov     rcx, [rel dx_cur]
    cmp     rcx, [rel dx_end]
    jae     dx_rd_fail
    movzx   eax, byte [rcx]
    inc     rcx
    mov     [rel dx_cur], rcx
    ret

dx_rd_fail:
    mov     byte [rel dx_fail], 1
    xor     eax, eax
    ret

; dx_rd16 / dx_rd32 / dx_rd64: rax = next value, zero-extended
dx_rd16:
    mov     rcx, [rel dx_cur]
    lea     rdx, [rcx + 2]
    cmp     rdx, [rel dx_end]
    ja      dx_rd_fail
    movzx   eax, word [rcx]
    mov     [rel dx_cur], rdx
    ret
dx_rd32:
    mov     rcx, [rel dx_cur]
    lea     rdx, [rcx + 4]
    cmp     rdx, [rel dx_end]
    ja      dx_rd_fail
    mov     eax, [rcx]
    mov     [rel dx_cur], rdx
    ret
dx_rd64:
    mov     rcx, [rel dx_cur]
    lea     rdx, [rcx + 8]
    cmp     rdx, [rel dx_end]
    ja      dx_rd_fail
    mov     rax, [rcx]
    mov     [rel dx_cur], rdx
    ret

; ============================================================================
; ModRM / SIB
; ============================================================================

dx_modrm_decode:
    call    dx_rd8
    mov     [rel dx_modrm], al
    mov     edx, eax
    shr     edx, 6
    mov     [rel dx_mod], dl
    mov     edx, eax
    shr     edx, 3
    and     edx, 7
    test    byte [rel dx_rex], 4           ; REX.R
    jz      .reg
    or      edx, 8
.reg:
    mov     [rel dx_regno], dl
    and     eax, 7                         ; rm
    mov     byte [rel dx_base], NO_REG
    mov     byte [rel dx_index], NO_REG
    mov     byte [rel dx_scale], 1
    mov     byte [rel dx_hasdisp], 0
    mov     qword [rel dx_disp], 0

    cmp     byte [rel dx_mod], 3
    jne     .memory
    test    byte [rel dx_rex], 1           ; REX.B
    jz      .rmreg
    or      eax, 8
.rmreg:
    mov     [rel dx_rmreg], al
    ret

.memory:
    cmp     eax, 4
    je      .sib
    cmp     eax, 5
    jne     .base_rm
    cmp     byte [rel dx_mod], 0
    jne     .base_rm
    mov     byte [rel dx_base], RIP_REG    ; [rip + disp32]
    jmp     .disp32
.base_rm:
    test    byte [rel dx_rex], 1
    jz      .base_set
    or      eax, 8
.base_set:
    mov     [rel dx_base], al
    jmp     .disp

.sib:
    call    dx_rd8
    mov     edx, eax
    shr     edx, 6
    mov     cl, dl
    mov     dl, 1
    shl     dl, cl
    mov     [rel dx_scale], dl
    mov     edx, eax
    shr     edx, 3
    and     edx, 7
    test    byte [rel dx_rex], 2           ; REX.X
    jz      .idx
    or      edx, 8
.idx:
    cmp     edx, 4
    je      .no_index                      ; index 100 without REX.X: none
    mov     [rel dx_index], dl
.no_index:
    and     eax, 7                         ; SIB base
    cmp     eax, 5
    jne     .sib_base
    cmp     byte [rel dx_mod], 0
    je      .disp32                        ; no base, disp32
.sib_base:
    test    byte [rel dx_rex], 1
    jz      .sib_base_set
    or      eax, 8
.sib_base_set:
    mov     [rel dx_base], al

.disp:
    cmp     byte [rel dx_mod], 1
    je      .disp8
    cmp     byte [rel dx_mod], 2
    je      .disp32
    ret
.disp8:
    call    dx_rd8
    movsx   rax, al
    movzx   ecx, byte [rel dx_disp8n]      ; EVEX compressed displacement
    imul    rax, rcx
    mov     [rel dx_disp], rax
    mov     byte [rel dx_hasdisp], 1
    ret
.disp32:
    call    dx_rd32
    movsxd  rax, eax
    mov     [rel dx_disp], rax
    mov     byte [rel dx_hasdisp], 1
    ret

; ============================================================================
; Output helpers
; ============================================================================

; dx_puts: append the string at rsi
dx_puts:
    mov     rdi, [rel dx_fb]
    jmp     fmt_str

; dx_putc: append the character in esi
dx_putc:
    mov     rdi, [rel dx_fb]
    jmp     fmt_char

; dx_hex: append "0x" + hex of rsi
dx_hex:
    push    rsi
    mov     esi, '0'
    call    dx_putc
    mov     esi, 'x'
    call    dx_putc
    pop     rsi
dx_hexraw:
    mov     rdi, [rel dx_fb]
    mov     edx, 1
    jmp     fmt_hex

; dx_imm: append rsi (already sign/zero-extended) masked to the operand size
dx_imm:
    movzx   ecx, byte [rel dx_osz]
    cmp     ecx, 64
    je      dx_hex
    mov     rax, 1
    shl     rax, cl
    dec     rax
    and     rsi, rax
    jmp     dx_hex

; dx_mnemonic: the mnemonic (with lock/rep already written), padded as
; objdump pads it when operands follow (esi != 0)
dx_mnemonic:
    push    rsi
    cmp     byte [rel dx_lock], 0
    je      .no_lock
    lea     rsi, [rel s_lock]
    call    dx_puts
.no_lock:
    cmp     byte [rel dx_vpfx], 0
    je      .no_v
    mov     esi, 'v'
    call    dx_putc
.no_v:
    mov     rsi, [rel dx_mnem]
    call    dx_puts
    pop     rsi
    test    esi, esi
    jz      .done
    ; pad to 6 columns after the start, then one space
    mov     rdi, [rel dx_fb]
    mov     rdx, [rel dx_textpos]
    add     rdx, 6
    sub     rdx, [rdi + FMTBUF_len]
    jle     .space
    mov     esi, ' '
    call    fmt_pad
.space:
    mov     esi, ' '
    call    dx_putc
.done:
    ret

; dx_sep: ","
dx_sep:
    mov     esi, ','
    jmp     dx_putc

; dx_reg: register name. edi = size (8/16/32/64), esi = number (0-15)
dx_reg:
    lea     rax, [rel r64]
    cmp     edi, 64
    je      .have
    lea     rax, [rel r32]
    cmp     edi, 32
    je      .have
    lea     rax, [rel r16]
    cmp     edi, 16
    je      .have
    lea     rax, [rel r8rex]
    cmp     byte [rel dx_rex], 0
    jne     .have
    lea     rax, [rel r8leg]
.have:
    and     esi, 15
    lea     rsi, [rax + rsi*8]
    jmp     dx_puts

; dx_mem: memory operand. edi = size in bits (0 = print no size)
dx_mem:
    push    rbx
    test    edi, edi
    jz      .no_size
    lea     rsi, [rel s_byte]
    cmp     edi, 8
    je      .size
    lea     rsi, [rel s_word]
    cmp     edi, 16
    je      .size
    lea     rsi, [rel s_dword]
    cmp     edi, 32
    je      .size
    lea     rsi, [rel s_xmmword]
    cmp     edi, 128
    je      .size
    lea     rsi, [rel s_ymmword]
    cmp     edi, 256
    je      .size
    lea     rsi, [rel s_tbyte]
    cmp     edi, 80
    je      .size
    lea     rsi, [rel s_zmmword]
    cmp     edi, 512
    je      .size
    lea     rsi, [rel s_dword_bcst]        ; EVEX broadcast: 0x100 + element bits
    cmp     edi, 0x120
    je      .size
    lea     rsi, [rel s_qword_bcst]
    cmp     edi, 0x140
    je      .size
    lea     rsi, [rel s_oword]
    cmp     edi, 0x180
    je      .size
    lea     rsi, [rel s_qword]
.size:
    call    dx_puts
.no_size:
    movzx   ebx, byte [rel dx_seg]
    test    ebx, ebx
    jz      .no_seg
    mov     esi, ebx
    call    dx_putc
    mov     esi, 's'
    call    dx_putc
    mov     esi, ':'
    call    dx_putc
.no_seg:
    ; absolute [disp32]: ds:0x...
    cmp     byte [rel dx_base], NO_REG
    jne     .bracket
    cmp     byte [rel dx_index], NO_REG
    jne     .bracket
    test    ebx, ebx
    jnz     .abs_value
    lea     rsi, [rel s_ds]
    call    dx_puts
.abs_value:
    mov     rsi, [rel dx_disp]
    call    dx_hex
    pop     rbx
    ret

.bracket:
    mov     esi, '['
    call    dx_putc
    xor     ebx, ebx                       ; ebx = something printed
    movzx   eax, byte [rel dx_base]
    cmp     eax, NO_REG
    je      .index
    cmp     eax, RIP_REG
    jne     .base_reg
    lea     rsi, [rel s_rip]
    cmp     byte [rel dx_p67], 0
    je      .rip_name
    lea     rsi, [rel s_eip]
.rip_name:
    call    dx_puts
    mov     ebx, 1
    jmp     .index
.base_reg:
    call    .addr_size
    mov     esi, eax
    call    dx_reg
    mov     ebx, 1
.index:
    movzx   eax, byte [rel dx_index]
    cmp     eax, NO_REG
    je      .disp
    test    ebx, ebx
    jz      .index_reg
    push    rax
    mov     esi, '+'
    call    dx_putc
    pop     rax
.index_reg:
    call    .addr_size
    mov     esi, eax
    call    dx_reg
    mov     esi, '*'
    call    dx_putc
    movzx   esi, byte [rel dx_scale]
    add     esi, '0'
    call    dx_putc
.disp:
    cmp     byte [rel dx_hasdisp], 0
    je      .close
    mov     rsi, [rel dx_disp]
    cmp     byte [rel dx_base], RIP_REG
    je      .plus                          ; rip: objdump shows +0xffff...
    test    rsi, rsi
    js      .minus
.plus:
    push    rsi
    mov     esi, '+'
    call    dx_putc
    pop     rsi
    call    dx_hex
    jmp     .close
.minus:
    neg     rsi
    push    rsi
    mov     esi, '-'
    call    dx_putc
    pop     rsi
    call    dx_hex
.close:
    mov     esi, ']'
    call    dx_putc
    pop     rbx
    ret
.addr_size:                                ; edi = 32 under a 67 prefix, else 64
    mov     edi, 64
    cmp     byte [rel dx_p67], 0
    je      .addr_ret
    mov     edi, 32
.addr_ret:
    ret

; dx_rm: the ModRM r/m operand at size edi (register or memory)
dx_rm:
    cmp     byte [rel dx_mod], 3
    jne     dx_mem
    movzx   esi, byte [rel dx_rmreg]
    jmp     dx_reg

; dx_greg: the ModRM reg operand at size edi
dx_greg:
    movzx   esi, byte [rel dx_regno]
    jmp     dx_reg

; dx_opreg: register encoded in the opcode's low bits (+ REX.B), size edi
dx_opreg:
    movzx   esi, byte [rel dx_op]
    and     esi, 7
    test    byte [rel dx_rex], 1
    jz      dx_reg
    or      esi, 8
    jmp     dx_reg

; dx_branch: rsi = sign-extended displacement; prints the target address
dx_branch:
    mov     rax, [rel dx_cur]
    sub     rax, [rel dx_start]
    add     rax, [rel dx_addr]             ; address of the next instruction
    add     rsi, rax
    mov     [rel dx_target], rsi
    jmp     dx_hexraw

; ============================================================================
; x87 floating point
; ============================================================================

; dx_x87: prints an x87 instruction (opcode D8-DF) whose ModRM is decoded.
; Memory forms come from x87_mem by (opcode - D8) * 8 + ModRM.reg, register
; forms from x87_reg by the same index, and the register encodings that are
; whole instructions of their own (fchs, fld1, fnstsw ax, ...) from x87_fix.
; Sets dx_fail for an invalid encoding.
dx_x87:
    push    rbx
    movzx   ebx, byte [rel dx_op]
    sub     ebx, 0xD8
    shl     ebx, 3
    movzx   eax, byte [rel dx_modrm]
    shr     eax, 3
    and     eax, 7
    add     ebx, eax                       ; (opcode - D8) * 8 + reg
    shl     ebx, 4                         ; 16-byte entries
    cmp     byte [rel dx_mod], 3
    je      .reg

    ; memory: name + operand size in bytes
    lea     rax, [rel x87_mem]
    add     rbx, rax
    cmp     byte [rbx + 15], 0xFF
    je      .fail
    mov     [rel dx_mnem], rbx
    call    dx_x87_wait
    mov     esi, 1
    call    dx_mnemonic
    movzx   edi, byte [rbx + 15]
    shl     edi, 3                         ; bits (0 = no size, 80 = TBYTE)
    call    dx_mem
    jmp     .done

.reg:
    lea     rax, [rel x87_reg]
    add     rbx, rax
    cmp     byte [rbx], 0
    je      .fixed
    mov     [rel dx_mnem], rbx
    mov     esi, 1
    call    dx_mnemonic
    movzx   eax, byte [rbx + 15]
    cmp     eax, 2
    je      .sti_st
    cmp     eax, 1
    jne     .sti
    lea     rsi, [rel s_st]                ; st,st(i)
    call    dx_puts
    mov     esi, ','
    call    dx_putc
.sti:
    call    .put_sti                       ; st(i)
    jmp     .done
.sti_st:
    call    .put_sti                       ; st(i),st
    lea     rsi, [rel s_commast]
    call    dx_puts
    jmp     .done

.fixed:
    ; the whole ModRM byte selects the instruction
    lea     rbx, [rel x87_fix]
    movzx   ecx, byte [rel dx_op]
    movzx   edx, byte [rel dx_modrm]
.fix_scan:
    movzx   eax, byte [rbx]
    test    eax, eax
    jz      .fail
    cmp     eax, ecx
    jne     .fix_next
    cmp     dl, [rbx + 1]
    je      .fix_hit
.fix_next:
    add     rbx, 16
    jmp     .fix_scan
.fix_hit:
    lea     rax, [rbx + 2]
    mov     [rel dx_mnem], rax
    call    dx_x87_wait
    movzx   esi, byte [rbx + 15]
    call    dx_mnemonic
    cmp     byte [rbx + 15], 0
    je      .done
    xor     esi, esi                       ; fnstsw ax
    mov     edi, 16
    call    dx_reg
    jmp     .done

.fail:
    mov     byte [rel dx_fail], 1
.done:
    pop     rbx
    ret

; "st(i)" from ModRM.rm (REX.B does not apply to the x87 stack)
.put_sti:
    lea     rsi, [rel s_st]
    call    dx_puts
    mov     esi, '('
    call    dx_putc
    movzx   esi, byte [rel dx_modrm]
    and     esi, 7
    add     esi, '0'
    call    dx_putc
    mov     esi, ')'
    jmp     dx_putc

; dx_x87_wait: after a folded 9B, "fnstsw" becomes "fstsw" (and so on)
dx_x87_wait:
    cmp     byte [rel dx_fwait], 0
    je      .ret
    mov     rsi, [rel dx_mnem]
    lea     rdi, [rel dx_namebuf]
    mov     byte [rdi], 'f'
    add     rsi, 2
    inc     rdi
.copy:
    mov     al, [rsi]
    mov     [rdi], al
    inc     rsi
    inc     rdi
    test    al, al
    jnz     .copy
    lea     rax, [rel dx_namebuf]
    mov     [rel dx_mnem], rax
.ret:
    ret

; dx_fwait_combo: eax = 1 when the bytes after a 9B are one of the "fn"
; instructions objdump folds it into: fnstenv/fnstcw (D9 /6 /7), fnsave/
; fnstsw (DD /6 /7), fnclex/fninit (DB E2/E3), fnstsw ax (DF E0)
dx_fwait_combo:
    mov     rcx, [rel dx_cur]
    lea     rdx, [rcx + 2]
    cmp     rdx, [rel dx_end]
    ja      .no
    movzx   eax, byte [rcx]
    movzx   edx, byte [rcx + 1]
    cmp     eax, 0xDB
    je      .db
    cmp     eax, 0xDF
    je      .df
    cmp     edx, 0xC0
    jae     .no                            ; D9 / DD: memory forms only
    shr     edx, 3
    and     edx, 7
    cmp     eax, 0xD9
    je      .d9dd
    cmp     eax, 0xDD
    jne     .no
.d9dd:
    cmp     edx, 6
    jae     .yes
    jmp     .no
.db:
    cmp     edx, 0xE2
    je      .yes
    cmp     edx, 0xE3
    je      .yes
    jmp     .no
.df:
    cmp     edx, 0xE0
    je      .yes
.no:
    xor     eax, eax
    ret
.yes:
    mov     eax, 1
    ret

; ============================================================================
; EVEX (AVX-512)
; ============================================================================

; dx_evex_find: r12 = the x86_evex entry with key ecx, or 0
dx_evex_find:
    lea     r12, [rel x86_evex]
.scan:
    mov     eax, [r12]
    test    eax, eax
    jz      .none
    cmp     eax, ecx
    je      .ret
    add     r12, 16
    jmp     .scan
.none:
    xor     r12d, r12d
.ret:
    ret

; dx_evex_bytes: eax = size in bytes of the memory operand (not a broadcast)
dx_evex_bytes:
    movzx   ecx, byte [rel dx_vl]
    mov     edx, 16
    shl     edx, cl                        ; vector length in bytes
    movzx   eax, byte [rel dx_emsize]
    test    eax, eax
    jz      .full
    cmp     eax, 4
    ja      .part
    lea     ecx, [rax - 1]                 ; b/w/d/q: 1/2/4/8
    mov     eax, 1
    shl     eax, cl
    ret
.part:
    cmp     eax, 8
    je      .x
    cmp     eax, 9
    je      .y
    lea     ecx, [rax - 4]                 ; half/quarter/eighth of the vector
    shr     edx, cl
.full:
    mov     eax, edx
    ret
.x:
    mov     eax, 16
    ret
.y:
    mov     eax, 32
    ret

; dx_evex_elem: eax = element size in bytes (8 with W, else 4)
dx_evex_elem:
    mov     eax, 4
    test    byte [rel dx_rex], 8
    jz      .ret
    mov     eax, 8
.ret:
    ret

; ---- dx_evex_operands --------------------
; Prints the mnemonic and the operands the entry's shape string lists (see
; x86_evex in scripts/gen_x86_tables.py), with {kN}{z} after the first one.
; r12 = the x86_evex entry.
dx_evex_operands:
    push    rbx
    push    r14
    ; vpclmulqdq: the four known selectors have names
    cmp     byte [rel dx_map], 4
    jne     .preds
    cmp     byte [rel dx_op], 0x44
    jne     .preds
    call    dx_peek
    cmp     byte [rel dx_fail], 0
    jne     .done
    lea     rsi, [rel s_pclmul_ll]
    cmp     eax, 0x00
    je      .pclmul
    lea     rsi, [rel s_pclmul_hl]
    cmp     eax, 0x01
    je      .pclmul
    lea     rsi, [rel s_pclmul_lh]
    cmp     eax, 0x10
    je      .pclmul
    lea     rsi, [rel s_pclmul_hh]
    cmp     eax, 0x11
    jne     .named
.pclmul:
    mov     [rel dx_mnem], rsi
    mov     byte [rel dx_vpfx], 1          ; "v" + pclmul...
    mov     byte [rel dx_epred], 1         ; the selector is in the name
    jmp     .named
.preds:
    ; vpcmp / vcmp: a known predicate goes into the name
    test    byte [rel dx_eflags], EV_PINT | EV_PFP
    jz      .named
    call    dx_peek
    cmp     byte [rel dx_fail], 0
    jne     .done
    test    byte [rel dx_eflags], EV_PFP
    jnz     .pfp
    cmp     eax, 3                         ; vpcmp: 0-2 and 4-6 have names
    je      .named
    cmp     eax, 7
    jae     .named
    mov     ecx, 5                         ; after "vpcmp"
    jmp     .pred
.pfp:
    cmp     eax, 32
    jae     .named
    mov     ecx, 4                         ; after "vcmp"
.pred:
    mov     byte [rel dx_epred], 1
    mov     rsi, [rel dx_mnem]
    lea     rdi, [rel dx_namebuf]
.p_head:
    mov     dl, [rsi]
    mov     [rdi], dl
    inc     rsi
    inc     rdi
    dec     ecx
    jnz     .p_head
    lea     rdx, [rel cmp_preds]
    shl     eax, 4
    add     rdx, rax
.p_pred:
    mov     al, [rdx]
    test    al, al
    jz      .p_tail
    mov     [rdi], al
    inc     rdx
    inc     rdi
    jmp     .p_pred
.p_tail:
    mov     al, [rsi]
    mov     [rdi], al
    inc     rsi
    inc     rdi
    test    al, al
    jnz     .p_tail
    lea     rax, [rel dx_namebuf]
    mov     [rel dx_mnem], rax
.named:
    mov     esi, 1
    call    dx_mnemonic
    lea     rbx, [r12 + 8]                 ; shape
    xor     r14d, r14d                     ; operands printed so far
.next:
    movzx   eax, byte [rbx]
    test    eax, eax
    jz      .done
    inc     rbx
    cmp     eax, 'H'
    jne     .not_h
    test    byte [rel dx_eflags], EV_MOVS
    jz      .not_h
    cmp     byte [rel dx_mod], 3
    jne     .next                          ; vmovss/vmovsd with memory: no H
.not_h:
    cmp     eax, 'I'
    jne     .sep
    cmp     byte [rel dx_epred], 0
    je      .sep
    call    dx_rd8                         ; the predicate, already named
    jmp     .next
.sep:
    test    r14d, r14d
    jz      .first
    push    rax
    call    dx_sep
    pop     rax
.first:
    call    .operand
    cmp     byte [rel dx_fail], 0
    jne     .done
    inc     r14d
    cmp     r14d, 1
    jne     .next
    call    .mask
    jmp     .next

.done:
    pop     r14
    pop     rbx
    ret

; one operand; eax = its letter
.operand:
    cmp     eax, 'V'
    je      .o_V
    cmp     eax, 'H'
    je      .o_H
    cmp     eax, 'W'
    je      .o_W
    cmp     eax, 'Y'
    je      .o_Y
    cmp     eax, 'E'
    je      .o_E
    cmp     eax, 'G'
    je      .o_G
    cmp     eax, 'K'
    je      .o_K
    cmp     eax, 'k'
    je      .o_k
    cmp     eax, 'I'
    je      .o_I
.o_fail:
    mov     byte [rel dx_fail], 1
    ret
.o_V:
    call    .main_class
    movzx   esi, byte [rel dx_regno]
    movzx   eax, byte [rel dx_reghi]
    or      esi, eax
    jmp     dx_vecreg_c
.o_Y:
    movzx   edi, byte [rel dx_vl]          ; half the vector length, at least xmm
    test    edi, edi
    jnz     .y_class
    mov     edi, 1
.y_class:
    movzx   esi, byte [rel dx_regno]
    movzx   eax, byte [rel dx_reghi]
    or      esi, eax
    jmp     dx_vecreg_c
.o_H:
    call    .main_class
    movzx   esi, byte [rel dx_vvvv]
    jmp     dx_vecreg_c
.o_W:
    cmp     byte [rel dx_mod], 3
    jne     .memory
    call    dx_evex_bytes                  ; register as wide as the memory form
    mov     edi, 1
    cmp     eax, 32
    jb      .w_reg
    mov     edi, 2
    je      .w_reg
    mov     edi, 3
.w_reg:
    movzx   esi, byte [rel dx_rmreg]
    movzx   eax, byte [rel dx_rmhi]
    or      esi, eax
    call    dx_vecreg_c
    jmp     .round
.o_E:
    cmp     byte [rel dx_mod], 3
    jne     .memory
    call    .gpr_size
    movzx   esi, byte [rel dx_rmreg]
    call    dx_reg
    jmp     .round
.o_G:
    call    .gpr_size
    movzx   esi, byte [rel dx_regno]
    jmp     dx_reg
.o_K:
    movzx   esi, byte [rel dx_regno]
    jmp     dx_kreg
.o_k:
    cmp     byte [rel dx_mod], 3
    jne     .o_fail
    movzx   esi, byte [rel dx_rmreg]
    jmp     dx_kreg
.o_I:
    call    dx_rd8
    mov     rsi, rax
    jmp     dx_hex

.memory:
    cmp     byte [rel dx_eb], 0
    je      .m_plain
    call    dx_evex_elem                   ; "DWORD BCST [...]"
    mov     edi, 0x120
    cmp     eax, 8
    jne     .m_put
    mov     edi, 0x140
    jmp     .m_put
.m_plain:
    call    dx_evex_bytes
    mov     edi, eax
    shl     edi, 3
.m_put:
    jmp     dx_mem

; {rn-sae} / {sae} after a register source when EVEX.b is set
.round:
    cmp     byte [rel dx_eb], 0
    je      .r_ret
    lea     rsi, [rel s_sae]
    test    byte [rel dx_eflags], EV_ER
    jz      .r_put
    movzx   eax, byte [rel dx_eround]
    shl     eax, 4
    lea     rsi, [rel s_rounds]
    add     rsi, rax
.r_put:
    jmp     dx_puts
.r_ret:
    ret

; edi = register class of V and H
.main_class:
    mov     edi, 1
    test    byte [rel dx_eflags], EV_SCALAR
    jnz     .mc_ret
    movzx   edi, byte [rel dx_vl]
    inc     edi
.mc_ret:
    ret

; edi = 64 with W, else 32
.gpr_size:
    mov     edi, 32
    test    byte [rel dx_rex], 8
    jz      .gs_ret
    mov     edi, 64
.gs_ret:
    ret

; "{kN}" when a mask is applied, "{z}" when zeroing
.mask:
    movzx   eax, byte [rel dx_eaaa]
    test    eax, eax
    jz      .no_k
    lea     rsi, [rel s_kopen]
    call    dx_puts
    movzx   esi, byte [rel dx_eaaa]
    add     esi, '0'
    call    dx_putc
    mov     esi, '}'
    call    dx_putc
.no_k:
    cmp     byte [rel dx_ez], 0
    je      .mask_ret
    lea     rsi, [rel s_zmask]
    jmp     dx_puts
.mask_ret:
    ret

; dx_kreg: mask register k(esi & 7)
dx_kreg:
    and     esi, 7
    push    rsi
    mov     esi, 'k'
    call    dx_putc
    pop     rsi
    add     esi, '0'
    jmp     dx_putc

; ---- k-mask instructions (VEX) -----------

; dx_kop_find: rax = the x86_kops entry for this VEX instruction, or 0.
; ecx = VEX.pp (kept).
dx_kop_find:
    lea     rax, [rel x86_kops]
    mov     edx, ecx
    test    byte [rel dx_rex], 8
    jz      .scan
    or      edx, 4                         ; pp | W << 2
.scan:
    cmp     byte [rax], 0
    je      .none
    movzx   r8d, byte [rax]
    movzx   r9d, byte [rel dx_map]
    cmp     r8d, r9d
    jne     .next
    movzx   r8d, byte [rax + 1]
    movzx   r9d, byte [rel dx_op]
    cmp     r8d, r9d
    jne     .next
    movzx   r8d, byte [rax + 2]
    cmp     r8d, edx
    je      .ret
.next:
    add     rax, 16
    jmp     .scan
.none:
    xor     eax, eax
.ret:
    ret

; dx_kop: prints the k-mask instruction whose x86_kops entry is r12
dx_kop:
    push    rbx
    mov     rbx, r12
    xor     eax, eax                       ; VEX.L: 1 for k,k,k forms, else 0
    cmp     byte [rbx + 3], 1
    jne     .l
    mov     eax, 1
.l:
    cmp     [rel dx_vl], al
    jne     .fail
    lea     rax, [rbx + 4]
    mov     [rel dx_mnem], rax
    movzx   eax, byte [rbx + 3]
    cmp     byte [rel dx_mod], 3
    je      .regs
    cmp     eax, 2                         ; only kmov has memory forms
    je      .go
    cmp     eax, 3
    je      .go
    jmp     .fail
.regs:
    cmp     eax, 3
    je      .fail
.go:
    mov     esi, 1
    call    dx_mnemonic
    movzx   eax, byte [rbx + 3]
    cmp     eax, 3
    je      .s_store
    cmp     eax, 5
    je      .s_gpr_k
    movzx   esi, byte [rel dx_regno]       ; k from ModRM.reg first
    call    dx_kreg
    call    dx_sep
    movzx   eax, byte [rbx + 3]
    cmp     eax, 1
    je      .s_three
    cmp     eax, 4
    je      .s_k_gpr
    cmp     byte [rel dx_mod], 3
    jne     .s_mem
    movzx   esi, byte [rel dx_rmreg]
    call    dx_kreg
    cmp     byte [rbx + 3], 7
    jne     .done
    call    dx_sep
    call    dx_rd8
    mov     rsi, rax
    call    dx_hex
    jmp     .done
.s_three:
    movzx   esi, byte [rel dx_vvvv]
    call    dx_kreg
    call    dx_sep
    movzx   esi, byte [rel dx_rmreg]
    call    dx_kreg
    jmp     .done
.s_k_gpr:
    call    .gpr_size
    movzx   esi, byte [rel dx_rmreg]
    call    dx_reg
    jmp     .done
.s_mem:
    call    .mem_size
    call    dx_mem
    jmp     .done
.s_store:
    call    .mem_size
    call    dx_mem
    call    dx_sep
    movzx   esi, byte [rel dx_regno]
    call    dx_kreg
    jmp     .done
.s_gpr_k:
    call    .gpr_size
    movzx   esi, byte [rel dx_regno]
    call    dx_reg
    call    dx_sep
    movzx   esi, byte [rel dx_rmreg]
    call    dx_kreg
    jmp     .done
.fail:
    mov     byte [rel dx_fail], 1
.done:
    pop     rbx
    ret

; edi = 64 for kmovq, else 32
.gpr_size:
    mov     edi, 32
    test    byte [rel dx_rex], 8
    jz      .gs_ret
    mov     edi, 64
.gs_ret:
    ret

; edi = memory size from the name's last letter (b/w/d/q)
.mem_size:
    lea     rsi, [rbx + 4]
.ms_end:
    cmp     byte [rsi + 1], 0
    je      .ms_last
    inc     rsi
    jmp     .ms_end
.ms_last:
    mov     edi, 8
    cmp     byte [rsi], 'b'
    je      .ms_ret
    mov     edi, 16
    cmp     byte [rsi], 'w'
    je      .ms_ret
    mov     edi, 32
    cmp     byte [rsi], 'd'
    je      .ms_ret
    mov     edi, 64
.ms_ret:
    ret

; ============================================================================
; Operands, by form
; ============================================================================

dx_operands:
    push    rbx
    movzx   ebx, byte [rel dx_osz]         ; ebx = operand size
    movzx   eax, byte [rel dx_form]

    cmp     eax, FM_NONE
    je      .f_none
    cmp     eax, FM_EbGb
    je      .f_EG
    cmp     eax, FM_EvGv
    je      .f_EG
    cmp     eax, FM_EvGv_bt
    je      .f_EG
    cmp     eax, FM_GbEb
    je      .f_GE
    cmp     eax, FM_GvEv
    je      .f_GE
    cmp     eax, FM_ALIb
    je      .f_accI
    cmp     eax, FM_eAXIz
    je      .f_accI
    cmp     eax, FM_Zv
    je      .f_Zv
    cmp     eax, FM_ZbIb
    je      .f_ZI
    cmp     eax, FM_ZvIv
    je      .f_ZvIv
    cmp     eax, FM_Jb
    je      .f_Jb
    cmp     eax, FM_Jz
    je      .f_Jz
    cmp     eax, FM_Eb
    je      .f_E
    cmp     eax, FM_Ev
    je      .f_E
    cmp     eax, FM_EbIb
    je      .f_EI
    cmp     eax, FM_EvIz
    je      .f_EI
    cmp     eax, FM_EvIb
    je      .f_EI
    cmp     eax, FM_Eb1
    je      .f_E1
    cmp     eax, FM_Ev1
    je      .f_E1
    cmp     eax, FM_EbCL
    je      .f_ECL
    cmp     eax, FM_EvCL
    je      .f_ECL
    cmp     eax, FM_EbIbU
    je      .f_EIU
    cmp     eax, FM_EvIbU
    je      .f_EIU
    cmp     eax, FM_GvM
    je      .f_GM
    cmp     eax, FM_GvEvIz
    je      .f_GEI
    cmp     eax, FM_GvEvIb
    je      .f_GEI
    cmp     eax, FM_GvEb
    je      .f_GEx
    cmp     eax, FM_GvEw
    je      .f_GEx
    cmp     eax, FM_GvEd
    je      .f_GEx
    cmp     eax, FM_IbU
    je      .f_IbU
    cmp     eax, FM_IbS
    je      .f_IbS
    cmp     eax, FM_Iz
    je      .f_Iz
    cmp     eax, FM_Iw
    je      .f_Iw
    cmp     eax, FM_ZvXchg
    je      .f_xchg
    cmp     eax, FM_EvGvIb
    je      .f_EGI
    cmp     eax, FM_EvGvCL
    je      .f_EGCL
    cmp     eax, FM_STR
    je      .f_str
    cmp     eax, FM_XCHG90
    je      .f_90
    cmp     eax, FM_CBW
    je      .f_cbw
    cmp     eax, FM_CWD
    je      .f_cwd
    cmp     eax, FM_Ewv
    je      .f_Ewv
    cmp     eax, FM_G7
    je      .f_g7
    cmp     eax, FM_GAE
    je      .f_gae
    cmp     eax, FM_EVEX
    je      .f_evex
    cmp     eax, FM_G9
    je      .f_g9
    cmp     eax, FM_VW
    jb      .unknown_form
    call    dx_sse_operands
    jmp     .done
.f_evex:
    call    dx_evex_operands
    jmp     .done

.f_g9:                                     ; 0F C7
    movzx   eax, byte [rel dx_regno]
    and     eax, 7
    cmp     byte [rel dx_mod], 3
    je      .g9_reg
    cmp     eax, 1                         ; cmpxchg8b m64 / cmpxchg16b m128
    jne     .sys_bad
    lea     rsi, [rel s_cmpxchg8b]
    mov     ebx, 64
    test    byte [rel dx_rex], 8
    jz      .g9_mem
    lea     rsi, [rel s_cmpxchg16b]
    mov     ebx, 0x180                     ; OWORD PTR
.g9_mem:
    mov     [rel dx_mnem], rsi
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_mem
    jmp     .done
.g9_reg:                                   ; rdrand / rdseed r16/32/64
    lea     rsi, [rel s_rdrand]
    cmp     eax, 6
    je      .g9_rput
    lea     rsi, [rel s_rdseed]
    cmp     eax, 7
    jne     .sys_bad
.g9_rput:
    mov     [rel dx_mnem], rsi
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    movzx   esi, byte [rel dx_rmreg]
    call    dx_reg
    jmp     .done
.unknown_form:
    mov     byte [rel dx_fail], 1
    jmp     .done

.f_Ewv:                                    ; register at operand size, memory WORD
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    cmp     byte [rel dx_mod], 3
    je      .ewv_put
    mov     edi, 16
.ewv_put:
    call    dx_rm
    jmp     .done

.f_g7:                                     ; 0F 01
    cmp     byte [rel dx_mod], 3
    je      .g7_reg
    lea     rsi, [rel g7_mem_names]
    lea     rdi, [rel g7_mem_sizes]
    jmp     .sys_mem
.g7_reg:
    ; smsw r / lmsw r (reg 4 / 6), else the whole ModRM byte selects it
    movzx   eax, byte [rel dx_regno]
    and     eax, 7
    cmp     eax, 4
    je      .g7_msw
    cmp     eax, 6
    je      .g7_msw
    lea     rsi, [rel g7_reg_names]
    movzx   eax, byte [rel dx_modrm]
.g7_scan:
    movzx   ecx, byte [rsi]
    test    ecx, ecx
    jz      .sys_bad
    cmp     ecx, eax
    je      .g7_found
    add     rsi, 16
    jmp     .g7_scan
.g7_found:
    inc     rsi
    mov     [rel dx_mnem], rsi
    jmp     .f_none
.g7_msw:
    shl     eax, 4
    lea     rsi, [rel g7_mem_names]
    add     rsi, rax
    mov     [rel dx_mnem], rsi
    cmp     byte [rel dx_regno], 6         ; lmsw takes a 16-bit register
    jne     .f_E
    and     byte [rel dx_regno], 7
    mov     ebx, 16
    jmp     .f_E

.f_gae:                                    ; 0F AE
    cmp     byte [rel dx_mod], 3
    je      .gae_reg
    lea     rsi, [rel gae_mem_names]
    lea     rdi, [rel gae_mem_sizes]
    jmp     .sys_mem
.gae_reg:                                  ; lfence / mfence / sfence
    movzx   eax, byte [rel dx_regno]
    and     eax, 7
    cmp     eax, 5
    jb      .sys_bad
    lea     rsi, [rel gae_reg_names]
    lea     rsi, [rsi + rax*8 - 40]
    mov     [rel dx_mnem], rsi
    jmp     .f_none

.sys_mem:                                  ; rsi = 16-byte name slots, rdi = sizes
    movzx   eax, byte [rel dx_regno]
    and     eax, 7
    movzx   ecx, byte [rdi + rax]
    cmp     ecx, 0xFF
    je      .sys_bad
    shl     eax, 4
    add     rsi, rax
    mov     [rel dx_mnem], rsi
    push    rcx
    push    rcx
    mov     esi, 1
    call    dx_mnemonic
    pop     rdi
    pop     rdi
    call    dx_mem                         ; edi = size (0 = none)
    jmp     .done
.sys_bad:
    mov     byte [rel dx_fail], 1
    jmp     .done

.f_none:
    xor     esi, esi
    call    dx_mnemonic
    jmp     .done

.f_EG:                                     ; r/m, reg
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_rm
    call    dx_sep
    mov     edi, ebx
    call    dx_greg
    jmp     .done

.f_GE:                                     ; reg, r/m
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_greg
    call    dx_sep
    mov     edi, ebx
    call    dx_rm
    jmp     .done

.f_accI:                                   ; al, imm8 / ax|eax|rax, imm16|32
    cmp     byte [rel dx_form], FM_ALIb
    jne     .acc_z
    call    dx_rd8
    jmp     .acc_have
.acc_z:
    call    .read_imm_z
.acc_have:
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    xor     esi, esi
    call    dx_reg
    call    dx_sep
    pop     rsi
    call    dx_imm
    jmp     .done

.f_Zv:                                     ; register in the opcode
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_opreg
    jmp     .done

.f_ZI:                                     ; r8 in opcode, imm8
    call    dx_rd8
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, 8
    call    dx_opreg
    call    dx_sep
    pop     rsi
    call    dx_imm
    jmp     .done

.f_ZvIv:                                   ; mov r, imm16/32 - or movabs r64, imm64
    cmp     ebx, 64
    jne     .zv_small
    call    dx_rd64
    push    rax
    lea     rax, [rel s_movabs]
    mov     [rel dx_mnem], rax
    jmp     .zv_print
.zv_small:
    call    .read_imm_z
    push    rax
.zv_print:
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_opreg
    call    dx_sep
    pop     rsi
    call    dx_imm
    jmp     .done

.f_Jb:
    call    dx_rd8
    movsx   rax, al
    jmp     .jump
.f_Jz:
    call    dx_rd32
    movsxd  rax, eax
.jump:
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    pop     rsi
    call    dx_branch
    jmp     .done

.f_E:                                      ; r/m
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_rm
    jmp     .done

.f_EI:                                     ; r/m, imm (Ib sign-extended / Iz)
    movzx   eax, byte [rel dx_form]
    cmp     eax, FM_EvIz
    je      .ei_z
    call    dx_rd8
    movsx   rax, al
    jmp     .ei_have
.ei_z:
    call    .read_imm_z
.ei_have:
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_rm
    call    dx_sep
    pop     rsi
    call    dx_imm
    jmp     .done

.f_E1:                                     ; r/m, 1
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_rm
    lea     rsi, [rel s_comma1]
    call    dx_puts
    jmp     .done

.f_ECL:                                    ; r/m, cl
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_rm
    lea     rsi, [rel s_commacl]
    call    dx_puts
    jmp     .done

.f_EIU:                                    ; r/m, imm8 (unsigned)
    call    dx_rd8
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_rm
    call    dx_sep
    pop     rsi
    call    dx_hex
    jmp     .done

.f_GM:                                     ; lea: reg, [mem] (no size)
    cmp     byte [rel dx_mod], 3
    jne     .gm_ok
    mov     byte [rel dx_fail], 1
    jmp     .done
.gm_ok:
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_greg
    call    dx_sep
    xor     edi, edi
    call    dx_mem
    jmp     .done

.f_GEI:                                    ; imul reg, r/m, imm
    movzx   eax, byte [rel dx_form]
    cmp     eax, FM_GvEvIz
    je      .gei_z
    call    dx_rd8
    movsx   rax, al
    jmp     .gei_have
.gei_z:
    call    .read_imm_z
.gei_have:
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_greg
    call    dx_sep
    mov     edi, ebx
    call    dx_rm
    call    dx_sep
    pop     rsi
    call    dx_imm
    jmp     .done

.f_GEx:                                    ; movzx/movsx/movsxd: reg, narrower r/m
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_greg
    call    dx_sep
    movzx   eax, byte [rel dx_form]
    mov     edi, 8
    cmp     eax, FM_GvEb
    je      .gex_src
    mov     edi, 16
    cmp     eax, FM_GvEw
    je      .gex_src
    mov     edi, 32
.gex_src:
    call    dx_rm
    jmp     .done

.f_IbU:                                    ; int imm8
    call    dx_rd8
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    pop     rsi
    call    dx_hex
    jmp     .done

.f_IbS:                                    ; push imm8 (sign-extended)
    call    dx_rd8
    movsx   rax, al
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    pop     rsi
    call    dx_imm
    jmp     .done

.f_Iz:                                     ; push imm32 (sign-extended)
    call    .read_imm_z
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    pop     rsi
    call    dx_imm
    jmp     .done

.f_Iw:                                     ; ret imm16
    call    dx_rd16
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    pop     rsi
    call    dx_hex
    jmp     .done

.f_xchg:                                   ; xchg r, rax (91-97)
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_opreg
    call    dx_sep
    mov     edi, ebx
    xor     esi, esi
    call    dx_reg
    jmp     .done

.f_EGI:                                    ; shld/shrd r/m, reg, imm8
    call    .shx_head
    call    dx_rd8
    mov     rsi, rax
    push    rsi
    call    dx_sep
    pop     rsi
    call    dx_hex
    jmp     .done
.f_EGCL:                                   ; shld/shrd r/m, reg, cl
    call    .shx_head
    lea     rsi, [rel s_commacl]
    call    dx_puts
    jmp     .done
.shx_head:
    mov     esi, 1
    call    dx_mnemonic
    mov     edi, ebx
    call    dx_rm
    call    dx_sep
    mov     edi, ebx
    jmp     dx_greg

.f_90:                                     ; nop / pause / xchg r8,rax / xchg ax,ax
    cmp     byte [rel dx_rep], 0
    je      .n90_rex
    lea     rax, [rel s_pause]
    mov     [rel dx_mnem], rax
    jmp     .f_none
.n90_rex:
    test    byte [rel dx_rex], 1
    jnz     .n90_xchg
    cmp     ebx, 16
    je      .n90_xchg
    test    byte [rel dx_rex], 8
    jz      .f_none                        ; plain nop
    lea     rax, [rel s_rexw_nop]          ; 48 90: objdump says "rex.W nop"
    mov     [rel dx_mnem], rax
    jmp     .f_none
.n90_xchg:
    lea     rax, [rel s_xchg]
    mov     [rel dx_mnem], rax
    jmp     .f_xchg

.f_cbw:
    lea     rax, [rel s_cbw]
    cmp     ebx, 16
    je      .cbw_set
    lea     rax, [rel s_cwde]
    cmp     ebx, 32
    je      .cbw_set
    lea     rax, [rel s_cdqe]
.cbw_set:
    mov     [rel dx_mnem], rax
    jmp     .f_none
.f_cwd:
    lea     rax, [rel s_cwd]
    cmp     ebx, 16
    je      .cbw_set
    lea     rax, [rel s_cdq]
    cmp     ebx, 32
    je      .cbw_set
    lea     rax, [rel s_cqo]
    jmp     .cbw_set

.f_str:
    call    dx_string
    jmp     .done

; .read_imm_z: rax = imm16 or imm32 (sign-extended), by operand size
.read_imm_z:
    cmp     ebx, 16
    jne     .rz32
    call    dx_rd16
    movsx   rax, ax
    ret
.rz32:
    call    dx_rd32
    movsxd  rax, eax
    ret

.done:
    pop     rbx
    ret

; ============================================================================
; SSE-family operands
; ============================================================================
; Operand kinds:  V = vector register from ModRM.reg
;                 W = vector register or memory from ModRM.rm
;                 U = vector register from ModRM.rm (register only)
;                 M = memory from ModRM.rm (memory only)
;                 E = general register or memory, G = general register
; Vector registers are mm0-7 (MMX forms) or xmm0-15. General registers are
; 64-bit with REX.W, else 32-bit.

dx_sse_operands:
    push    rbx
    ; REX.W / VEX.W turns a trailing 'd' into 'q' (movd -> movq, ...)
    test    byte [rel dx_sflags], SF_WQ
    jz      .no_wq
    test    byte [rel dx_rex], 8
    jz      .no_wq
    mov     esi, 'q'
    call    dx_name_last
.no_wq:
    ; VEX-only tables: VEX.W turns a trailing 's' into 'd' (ps -> pd)
    cmp     byte [rel dx_vex], 0
    je      .named
    cmp     byte [rel dx_vpfx], 0
    jne     .named
    test    byte [rel dx_sflags], VF_WSD
    jz      .named
    test    byte [rel dx_rex], 8
    jz      .named
    mov     esi, 'd'
    call    dx_name_last
.named:
    movzx   eax, byte [rel dx_form]
    cmp     eax, FM_VW
    je      .VW
    cmp     eax, FM_WV
    je      .WV
    cmp     eax, FM_VWI
    je      .VWI
    cmp     eax, FM_VE
    je      .VE
    cmp     eax, FM_EV
    je      .EV
    cmp     eax, FM_GW
    je      .GW
    cmp     eax, FM_GU
    je      .GU
    cmp     eax, FM_UI
    je      .UI
    cmp     eax, FM_VM
    je      .VM
    cmp     eax, FM_MV
    je      .MV
    cmp     eax, FM_V12
    je      .V12
    cmp     eax, FM_EVI
    je      .EVI
    cmp     eax, FM_VEI
    je      .VEI
    cmp     eax, FM_GUI
    je      .GUI
    cmp     eax, FM_VW0
    je      .VW0
    cmp     eax, FM_CMPS
    je      .CMPS
    cmp     eax, FM_PCLMUL
    je      .PCLMUL
    cmp     eax, FM_ENDBR
    je      .ENDBR
    cmp     eax, FM_XBCAST
    je      .XBCAST
    cmp     eax, FM_XINS
    je      .XINS
    cmp     eax, FM_XEXT
    je      .XEXT
    cmp     eax, FM_XIS4
    je      .XIS4
    cmp     eax, FM_BGBE
    je      .BGBE
    cmp     eax, FM_BGEB
    je      .BGEB
    cmp     eax, FM_BBE
    je      .BBE
    cmp     eax, FM_XMLD
    je      .XMLD
    cmp     eax, FM_XMST
    je      .XMST
    cmp     eax, FM_BRORX
    je      .BRORX
    cmp     eax, FM_XZERO
    je      .XZERO
    jmp     .fail

.VW:
    call    .mn
    call    dx_opV
    call    .nds
    call    dx_sep
    call    dx_opW
    jmp     .done
.WV:
    call    .mn
    call    dx_opW
    call    .movs_nds                      ; vmovss/vmovsd register store
    call    dx_sep
    call    dx_opV
    jmp     .done
.VWI:
    call    .mn
    call    dx_opV
    call    .nds
    call    dx_sep
    call    dx_opW
    jmp     .imm8
.VE:
    call    .mn
    call    dx_opV
    call    .nds
    call    dx_sep
    call    dx_opE
    jmp     .done
.EV:
    call    .mn
    call    dx_opE
    call    dx_sep
    call    dx_opV
    jmp     .done
.GW:
    call    .mn
    call    dx_opG
    call    dx_sep
    call    dx_opW
    jmp     .done
.GU:
    cmp     byte [rel dx_mod], 3
    jne     .fail
    call    .mn
    mov     edi, 32
    call    dx_greg
    call    dx_sep
    call    dx_opW
    jmp     .done
.UI:                                       ; group: the name comes from ModRM.reg
    cmp     byte [rel dx_mod], 3
    jne     .fail
    lea     rax, [rel x86_groups]
    movzx   ecx, word [r12]                ; group number (r12 = SSE entry)
    shl     ecx, 3
    movzx   edx, byte [rel dx_regno]
    and     edx, 7
    add     ecx, edx
    movzx   ecx, word [rax + rcx*4]
    cmp     ecx, 0xFFFF
    je      .fail
    lea     rax, [rel x86_names]
    add     rax, rcx
    mov     [rel dx_mnem], rax
    call    .mn
    cmp     byte [rel dx_vex], 0
    je      .ui_src
    movzx   esi, byte [rel dx_vvvv]        ; VEX: vvvv is the destination
    call    dx_vecreg
    call    dx_sep
.ui_src:
    call    dx_opW
    jmp     .imm8
.VM:
    cmp     byte [rel dx_mod], 3
    je      .fail
    call    .mn
    call    dx_opV
    call    .nds
    call    dx_sep
    call    dx_opW
    jmp     .done
.MV:
    cmp     byte [rel dx_mod], 3
    je      .fail
    call    .mn
    call    dx_opW
    call    dx_sep
    call    dx_opV
    jmp     .done
.V12:                                      ; movlps/movhps, or movhlps/movlhps
    cmp     byte [rel dx_mod], 3
    jne     .VW
    lea     rax, [rel s_movhlps]
    cmp     byte [rel dx_op], 0x12
    je      .v12_name
    lea     rax, [rel s_movlhps]
.v12_name:
    mov     [rel dx_mnem], rax
    jmp     .VW
.EVI:
    call    .mn
    call    dx_opE
    call    dx_sep
    call    dx_opV
    jmp     .imm8
.VEI:
    call    .mn
    call    dx_opV
    call    .nds
    call    dx_sep
    call    dx_opE
    jmp     .imm8
.GUI:
    cmp     byte [rel dx_mod], 3
    jne     .fail
    call    .mn
    mov     edi, 32
    call    dx_greg
    call    dx_sep
    call    dx_opW
    jmp     .imm8
.VW0:
    call    .mn
    call    dx_opV
    call    dx_sep
    call    dx_opW
    lea     rsi, [rel s_commaxmm0]
    call    dx_puts
    jmp     .done

.CMPS:                                     ; cmpps xmm,xmm,imm - or cmpltps xmm,xmm
    call    .peek_imm
    cmp     eax, 32
    jae     .VWI
    cmp     byte [rel dx_vex], 0
    jne     .cmps_pred                     ; VEX: 32 predicates, SSE: 8
    cmp     eax, 8
    jae     .VWI
.cmps_pred:
    ; "cmp" + predicate + the entry's suffix (ps/pd/ss/sd)
    lea     rdi, [rel dx_namebuf]
    mov     byte [rdi], 'c'
    mov     byte [rdi + 1], 'm'
    mov     byte [rdi + 2], 'p'
    add     rdi, 3
    lea     rsi, [rel cmp_preds]
    shl     eax, 4
    add     rsi, rax
.cmps_copy:
    mov     cl, [rsi]
    test    cl, cl
    jz      .cmps_suffix
    mov     [rdi], cl
    inc     rdi
    inc     rsi
    jmp     .cmps_copy
.cmps_suffix:
    mov     rsi, [rel dx_mnem]             ; "cmpps": suffix at +3
    mov     cl, [rsi + 3]
    mov     [rdi], cl
    mov     cl, [rsi + 4]
    mov     [rdi + 1], cl
    mov     byte [rdi + 2], 0
    lea     rax, [rel dx_namebuf]
    mov     [rel dx_mnem], rax
    call    .mn
    call    dx_opV
    call    .nds
    call    dx_sep
    call    dx_opW
    call    dx_rd8                         ; consume the predicate
    jmp     .done

.PCLMUL:                                   ; pclmulqdq: known selectors get names
    call    .peek_imm
    lea     rsi, [rel s_pclmul_ll]
    cmp     eax, 0x00
    je      .pcl_named
    lea     rsi, [rel s_pclmul_hl]
    cmp     eax, 0x01
    je      .pcl_named
    lea     rsi, [rel s_pclmul_lh]
    cmp     eax, 0x10
    je      .pcl_named
    lea     rsi, [rel s_pclmul_hh]
    cmp     eax, 0x11
    jne     .VWI
.pcl_named:
    mov     [rel dx_mnem], rsi
    call    .mn
    call    dx_opV
    call    .nds
    call    dx_sep
    call    dx_opW
    call    dx_rd8
    jmp     .done

; ---- VEX-only forms ----
.XZERO:
    cmp     byte [rel dx_vl], 0
    je      .zero_named
    lea     rax, [rel s_vzeroall]
    mov     [rel dx_mnem], rax
.zero_named:
    xor     esi, esi
    call    dx_mnemonic
    jmp     .done
.XBCAST:                                   ; V, xmm register or memory
    call    .mn
    call    dx_opV
    call    dx_sep
    cmp     byte [rel dx_mod], 3
    jne     .bcast_mem
    movzx   esi, byte [rel dx_rmreg]
    mov     edi, 1
    call    dx_vecreg_c
    jmp     .done
.bcast_mem:
    call    dx_memsize
    cmp     edi, 256
    jne     .mem_done
    mov     edi, 128
    jmp     .mem_done
.XINS:                                     ; ymm, ymm, xmm/m128, imm8
    call    .mn
    call    dx_opV
    call    .vvvv
    call    dx_sep
    call    .xmm_or_m128
    jmp     .imm8
.XEXT:                                     ; xmm/m128, ymm, imm8
    call    .mn
    call    .xmm_or_m128
    call    dx_sep
    call    dx_opV
    jmp     .imm8
.XIS4:                                     ; V, vvvv, W, register from imm8[7:4]
    call    .mn
    call    dx_opV
    call    .vvvv
    call    dx_sep
    call    dx_opW
    call    dx_sep
    call    dx_rd8
    shr     eax, 4
    mov     esi, eax
    call    dx_vecreg
    jmp     .done
.XMLD:                                     ; V, vvvv, memory
    cmp     byte [rel dx_mod], 3
    je      .fail
    call    .mn
    call    dx_opV
    call    .vvvv
    call    dx_sep
    call    dx_opW
    jmp     .done
.XMST:                                     ; memory, vvvv, V
    cmp     byte [rel dx_mod], 3
    je      .fail
    call    .mn
    call    dx_opW
    call    .vvvv
    call    dx_sep
    call    dx_opV
    jmp     .done
.BGBE:                                     ; gpr, vvvv, r/m
    call    .mn
    call    dx_opG
    call    dx_sep
    call    .vvvv_gpr
    call    dx_sep
    call    dx_opE
    jmp     .done
.BGEB:                                     ; gpr, r/m, vvvv
    call    .mn
    call    dx_opG
    call    dx_sep
    call    dx_opE
    call    dx_sep
    call    .vvvv_gpr
    jmp     .done
.BBE:                                      ; group: vvvv, r/m
    lea     rax, [rel x86_groups]
    movzx   ecx, word [r12]
    shl     ecx, 3
    movzx   edx, byte [rel dx_regno]
    and     edx, 7
    add     ecx, edx
    movzx   ecx, word [rax + rcx*4]
    cmp     ecx, 0xFFFF
    je      .fail
    lea     rax, [rel x86_names]
    add     rax, rcx
    mov     [rel dx_mnem], rax
    call    .mn
    call    .vvvv_gpr
    call    dx_sep
    call    dx_opE
    jmp     .done
.BRORX:                                    ; gpr, r/m, imm8
    call    .mn
    call    dx_opG
    call    dx_sep
    call    dx_opE
    jmp     .imm8

; ",vvvv" when this VEX instruction has an extra source register
.nds:
    cmp     byte [rel dx_vex], 0
    je      .nds_ret
    test    byte [rel dx_sflags], SF_NDS
    jz      .nds_ret
    ; vmovss/vmovsd (0F 10): only the register form has one
    cmp     byte [rel dx_map], 2
    jne     .vvvv
    cmp     byte [rel dx_op], 0x10
    jne     .vvvv
    cmp     byte [rel dx_mod], 3
    jne     .nds_ret
.vvvv:
    call    dx_sep
    movzx   esi, byte [rel dx_vvvv]
    jmp     dx_vecreg
.nds_ret:
    ret
; vmovss/vmovsd store (0F 11) register form: W, vvvv, V
.movs_nds:
    cmp     byte [rel dx_vex], 0
    je      .nds_ret
    cmp     byte [rel dx_map], 2
    jne     .nds_ret
    cmp     byte [rel dx_op], 0x11
    jne     .nds_ret
    cmp     byte [rel dx_mod], 3
    jne     .nds_ret
    movzx   eax, byte [rel dx_sflags]
    and     eax, SF_MEM
    cmp     eax, 5
    je      .nds_ret                       ; vmovups & co: no extra source
    jmp     .vvvv
; vvvv as a general register (BMI), 32/64 by VEX.W
.vvvv_gpr:
    mov     edi, 32
    test    byte [rel dx_rex], 8
    jz      .vg
    mov     edi, 64
.vg:
    movzx   esi, byte [rel dx_vvvv]
    jmp     dx_reg
; an xmm register or 128-bit memory operand (vinsert/vextract)
.xmm_or_m128:
    cmp     byte [rel dx_mod], 3
    jne     .m128
    movzx   esi, byte [rel dx_rmreg]
    mov     edi, 1
    jmp     dx_vecreg_c
.m128:
    mov     edi, 128
    jmp     dx_mem
.mem_done:
    call    dx_mem
    jmp     .done

.ENDBR:                                    ; F3 0F 1E FA / FB
    lea     rax, [rel s_endbr64]
    cmp     byte [rel dx_modrm], 0xFA
    je      .endbr_name
    lea     rax, [rel s_endbr32]
    cmp     byte [rel dx_modrm], 0xFB
    jne     .fail
.endbr_name:
    mov     [rel dx_mnem], rax
    xor     esi, esi
    call    dx_mnemonic
    jmp     .done

.imm8:
    call    dx_rd8
    mov     rsi, rax
    push    rsi
    call    dx_sep
    pop     rsi
    call    dx_hex
    jmp     .done

.fail:
    mov     byte [rel dx_fail], 1
.done:
    pop     rbx
    ret

.mn:
    mov     esi, 1
    jmp     dx_mnemonic

; the immediate after the ModRM operand, without consuming it
.peek_imm:
    mov     rcx, [rel dx_cur]
    cmp     rcx, [rel dx_end]
    jae     .peek_fail
    movzx   eax, byte [rcx]
    ret
.peek_fail:
    mov     byte [rel dx_fail], 1
    mov     eax, 0xFF
    ret

; ---- dx_name_last ------------------------
; Copies the mnemonic to dx_namebuf with its last character replaced by
; the character in esi ('q' for movd -> movq, 'd' for ...ps -> ...pd).
dx_name_last:
    mov     edx, esi
    mov     rsi, [rel dx_mnem]
    lea     rdi, [rel dx_namebuf]
.copy:
    mov     al, [rsi]
    mov     [rdi], al
    test    al, al
    jz      .copied
    inc     rsi
    inc     rdi
    jmp     .copy
.copied:
    mov     [rdi - 1], dl
    lea     rax, [rel dx_namebuf]
    mov     [rel dx_mnem], rax
    ret

; ---- vector operand printers ------------

; dx_vecreg: vector register esi ("mm3" / "xmm12")
dx_vecreg:
    movzx   edi, byte [rel dx_vclass]
; dx_vecreg_c: vector register esi of class edi (0 mm, 1 xmm, 2 ymm, 3 zmm)
dx_vecreg_c:
    push    rsi
    push    rdi
    lea     rsi, [rel s_mm]
    test    edi, edi
    jz      .prefix
    lea     rsi, [rel s_xmm]
    cmp     edi, 1
    je      .prefix
    lea     rsi, [rel s_ymm]
    cmp     edi, 2
    je      .prefix
    lea     rsi, [rel s_zmm]
.prefix:
    call    dx_puts
    pop     rdi
    pop     rsi
    test    edi, edi
    jnz     .num
    and     esi, 7
.num:
    mov     rdi, [rel dx_fb]
    jmp     fmt_udec

; dx_memsize: edi = memory operand size in bits for this entry (0 = none)
dx_memsize:
    movzx   eax, byte [rel dx_sflags]
    and     eax, SF_MEM
    ; W makes a DWORD operand QWORD where it also renames the instruction
    ; (pinsrd -> pinsrq, vfmadd213ss -> vfmadd213sd)
    cmp     eax, 3
    jne     .sized
    test    byte [rel dx_rex], 8
    jz      .sized
    test    byte [rel dx_sflags], SF_WQ
    jnz     .wide
    cmp     byte [rel dx_vex], 0
    je      .sized
    cmp     byte [rel dx_vpfx], 0
    jne     .sized
    test    byte [rel dx_sflags], VF_WSD
    jz      .sized
.wide:
    mov     eax, 4
.sized:
    xor     edi, edi
    cmp     eax, 1
    jne     .w
    mov     edi, 8
.w: cmp     eax, 2
    jne     .d
    mov     edi, 16
.d: cmp     eax, 3
    jne     .q
    mov     edi, 32
.q: cmp     eax, 4
    jne     .x
    mov     edi, 64
.x: cmp     eax, 5
    jne     .ret
    mov     edi, 64                        ; by register class: mm / xmm / ymm
    cmp     byte [rel dx_vclass], 0
    je      .ret
    mov     edi, 128
    cmp     byte [rel dx_vclass], 1
    je      .ret
    mov     edi, 256
.ret:
    ret

dx_opV:
    movzx   esi, byte [rel dx_regno]
    cmp     byte [rel dx_narrow], 0
    je      dx_vecreg
    mov     edi, 1                         ; narrowing conversion: always xmm
    jmp     dx_vecreg_c

dx_opW:
    cmp     byte [rel dx_half], 0
    jne     .half
    cmp     byte [rel dx_mod], 3
    jne     .mem
    movzx   esi, byte [rel dx_rmreg]
    jmp     dx_vecreg
.mem:
    call    dx_memsize
    jmp     dx_mem
.half:
    cmp     byte [rel dx_mod], 3
    jne     .half_mem
    movzx   esi, byte [rel dx_rmreg]
    mov     edi, 1                         ; always xmm
    jmp     dx_vecreg_c
.half_mem:
    call    dx_memsize
    cmp     byte [rel dx_vl], 0
    je      .half_put
    add     edi, edi                       ; ymm destination: twice the bytes
.half_put:
    jmp     dx_mem

; E: general register (32/64 by REX.W) or memory (entry size, else 32/64)
dx_opE:
    mov     edi, 32
    test    byte [rel dx_rex], 8
    jz      .sized
    mov     edi, 64
.sized:
    cmp     byte [rel dx_mod], 3
    jne     .mem
    movzx   esi, byte [rel dx_rmreg]
    jmp     dx_reg
.mem:
    push    rdi
    call    dx_memsize
    pop     rax
    test    edi, edi
    jnz     .have
    mov     edi, eax
.have:
    jmp     dx_mem

dx_opG:
    mov     edi, 32
    test    byte [rel dx_rex], 8
    jz      .reg
    mov     edi, 64
.reg:
    jmp     dx_greg

; ---- string instructions ----------------
;
; objdump spells them with explicit operands, e.g.
;   rep stos QWORD PTR es:[rdi],rax
;   movs BYTE PTR es:[rdi],BYTE PTR ds:[rsi]
;   repz cmps BYTE PTR ds:[rsi],BYTE PTR es:[rdi]
;   lods al,BYTE PTR ds:[rsi]        scas al,BYTE PTR es:[rdi]
;
dx_string:
    push    rbx
    movzx   ebx, byte [rel dx_osz]
    movzx   eax, byte [rel dx_op]
    and     eax, 0xFE                      ; A4/A6/AA/AC/AE family

    ; rep prefix spelling
    cmp     byte [rel dx_repne], 0
    je      .no_repne
    lea     rsi, [rel s_repnz]
    jmp     .prefix
.no_repne:
    cmp     byte [rel dx_rep], 0
    je      .mn
    lea     rsi, [rel s_rep]
    cmp     eax, 0xA6                      ; cmps
    je      .repz
    cmp     eax, 0xAE                      ; scas
    jne     .prefix
.repz:
    lea     rsi, [rel s_repz]
.prefix:
    push    rax
    call    dx_puts
    pop     rax
.mn:
    push    rax
    mov     esi, 1
    call    dx_mnemonic
    pop     rax

    cmp     eax, 0xA4
    je      .movs
    cmp     eax, 0xA6
    je      .cmps
    cmp     eax, 0xAA
    je      .stos
    cmp     eax, 0xAC
    je      .lods
    ; scas: acc, es:[rdi]
    call    .acc
    call    dx_sep
    call    .es_rdi
    jmp     .done
.movs:
    call    .es_rdi
    call    dx_sep
    call    .ds_rsi
    jmp     .done
.cmps:
    call    .ds_rsi
    call    dx_sep
    call    .es_rdi
    jmp     .done
.stos:
    call    .es_rdi
    call    dx_sep
    call    .acc
    jmp     .done
.lods:
    call    .acc
    call    dx_sep
    call    .ds_rsi
.done:
    pop     rbx
    ret

.acc:
    mov     edi, ebx
    xor     esi, esi
    jmp     dx_reg
.es_rdi:
    call    .size
    lea     rsi, [rel s_esrdi]
    jmp     dx_puts
.ds_rsi:
    call    .size
    lea     rsi, [rel s_dsrsi]
    jmp     dx_puts
.size:
    lea     rsi, [rel s_byte]
    cmp     ebx, 8
    je      .size_put
    lea     rsi, [rel s_word]
    cmp     ebx, 16
    je      .size_put
    lea     rsi, [rel s_dword]
    cmp     ebx, 32
    je      .size_put
    lea     rsi, [rel s_qword]
.size_put:
    jmp     dx_puts

[SECTION .rodata]
; register names, 8 bytes per slot
r64:    db "rax",0,0,0,0,0, "rcx",0,0,0,0,0, "rdx",0,0,0,0,0, "rbx",0,0,0,0,0
        db "rsp",0,0,0,0,0, "rbp",0,0,0,0,0, "rsi",0,0,0,0,0, "rdi",0,0,0,0,0
        db "r8",0,0,0,0,0,0, "r9",0,0,0,0,0,0, "r10",0,0,0,0,0, "r11",0,0,0,0,0
        db "r12",0,0,0,0,0, "r13",0,0,0,0,0, "r14",0,0,0,0,0, "r15",0,0,0,0,0
r32:    db "eax",0,0,0,0,0, "ecx",0,0,0,0,0, "edx",0,0,0,0,0, "ebx",0,0,0,0,0
        db "esp",0,0,0,0,0, "ebp",0,0,0,0,0, "esi",0,0,0,0,0, "edi",0,0,0,0,0
        db "r8d",0,0,0,0,0, "r9d",0,0,0,0,0, "r10d",0,0,0,0, "r11d",0,0,0,0
        db "r12d",0,0,0,0, "r13d",0,0,0,0, "r14d",0,0,0,0, "r15d",0,0,0,0
r16:    db "ax",0,0,0,0,0,0, "cx",0,0,0,0,0,0, "dx",0,0,0,0,0,0, "bx",0,0,0,0,0,0
        db "sp",0,0,0,0,0,0, "bp",0,0,0,0,0,0, "si",0,0,0,0,0,0, "di",0,0,0,0,0,0
        db "r8w",0,0,0,0,0, "r9w",0,0,0,0,0, "r10w",0,0,0,0, "r11w",0,0,0,0
        db "r12w",0,0,0,0, "r13w",0,0,0,0, "r14w",0,0,0,0, "r15w",0,0,0,0
r8rex:  db "al",0,0,0,0,0,0, "cl",0,0,0,0,0,0, "dl",0,0,0,0,0,0, "bl",0,0,0,0,0,0
        db "spl",0,0,0,0,0, "bpl",0,0,0,0,0, "sil",0,0,0,0,0, "dil",0,0,0,0,0
        db "r8b",0,0,0,0,0, "r9b",0,0,0,0,0, "r10b",0,0,0,0, "r11b",0,0,0,0
        db "r12b",0,0,0,0, "r13b",0,0,0,0, "r14b",0,0,0,0, "r15b",0,0,0,0
r8leg:  db "al",0,0,0,0,0,0, "cl",0,0,0,0,0,0, "dl",0,0,0,0,0,0, "bl",0,0,0,0,0,0
        db "ah",0,0,0,0,0,0, "ch",0,0,0,0,0,0, "dh",0,0,0,0,0,0, "bh",0,0,0,0,0,0
        db "r8b",0,0,0,0,0, "r9b",0,0,0,0,0, "r10b",0,0,0,0, "r11b",0,0,0,0
        db "r12b",0,0,0,0, "r13b",0,0,0,0, "r14b",0,0,0,0, "r15b",0,0,0,0

s_byte:     db "BYTE PTR ", 0
s_word:     db "WORD PTR ", 0
s_dword:    db "DWORD PTR ", 0
s_qword:    db "QWORD PTR ", 0
s_xmmword:  db "XMMWORD PTR ", 0
s_ymmword:  db "YMMWORD PTR ", 0
s_zmmword:  db "ZMMWORD PTR ", 0
s_dword_bcst: db "DWORD BCST ", 0
s_qword_bcst: db "QWORD BCST ", 0
s_zmm:      db "zmm", 0
s_oword:    db "OWORD PTR ", 0
s_cmpxchg8b: db "cmpxchg8b", 0
s_cmpxchg16b: db "cmpxchg16b", 0
s_rdrand:   db "rdrand", 0
s_rdseed:   db "rdseed", 0
s_vldmxcsr: db "vldmxcsr", 0
s_vstmxcsr: db "vstmxcsr", 0
s_kopen:    db "{k", 0
s_zmask:    db "{z}", 0
s_sae:      db "{sae}", 0
s_rounds:   db "{rn-sae}", 0, 0, 0, 0, 0, 0, 0, 0
            db "{rd-sae}", 0, 0, 0, 0, 0, 0, 0, 0
            db "{ru-sae}", 0, 0, 0, 0, 0, 0, 0, 0
            db "{rz-sae}", 0, 0, 0, 0, 0, 0, 0, 0
s_tbyte:    db "TBYTE PTR ", 0
s_st:       db "st", 0
s_commast:  db ",st", 0
s_data16:   db "data16 ", 0
s_mm:       db "mm", 0
s_xmm:      db "xmm", 0
s_ymm:      db "ymm", 0
s_vzeroall: db "vzeroall", 0
s_commaxmm0: db ",xmm0", 0
s_movhlps:  db "movhlps", 0
s_movlhps:  db "movlhps", 0
s_endbr64:  db "endbr64", 0
s_endbr32:  db "endbr32", 0
s_pclmul_ll: db "pclmullqlqdq", 0
s_pclmul_hl: db "pclmulhqlqdq", 0
s_pclmul_lh: db "pclmullqhqdq", 0
s_pclmul_hh: db "pclmulhqhqdq", 0
; cmpps predicates 0-7, 8-byte slots
; the 32 vcmp predicates (legacy SSE uses the first 8), 16 bytes each
cmp_preds:  db "eq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "lt", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "le", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "unord", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "neq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "nlt", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "nle", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "ord", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "eq_uq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "nge", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "ngt", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "false", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "neq_oq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "ge", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "gt", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "true", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "eq_os", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "lt_oq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "le_oq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "unord_s", 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "neq_us", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "nlt_uq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "nle_uq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "ord_s", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "eq_us", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "nge_uq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "ngt_uq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "false_os", 0, 0, 0, 0, 0, 0, 0, 0
            db "neq_os", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "ge_oq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "gt_oq", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
            db "true_us", 0, 0, 0, 0, 0, 0, 0, 0, 0
s_ds:       db "ds:", 0
s_rip:      db "rip", 0
s_eip:      db "eip", 0
s_lock:     db "lock ", 0
s_rep:      db "rep ", 0
s_repz:     db "repz ", 0
s_repnz:    db "repnz ", 0
s_notrack:  db "notrack ", 0
s_rexw:     db "rex.W ", 0
s_comma1:   db ",1", 0
s_commacl:  db ",cl", 0
s_esrdi:    db "es:[rdi]", 0
s_dsrsi:    db "ds:[rsi]", 0
s_movabs:   db "movabs", 0
s_pause:    db "pause", 0
s_xchg:     db "xchg", 0
s_cbw:      db "cbw", 0
s_cwde:     db "cwde", 0
s_cdqe:     db "cdqe", 0
s_cwd:      db "cwd", 0
s_cdq:      db "cdq", 0
s_cqo:      db "cqo", 0
s_rexw_nop: db "rex.W nop", 0

; 0F 01 with a memory operand, by ModRM.reg (16-byte slots) and operand size
g7_mem_names:  db "sgdt",0,0,0,0,0,0,0,0,0,0,0,0,  "sidt",0,0,0,0,0,0,0,0,0,0,0,0
               db "lgdt",0,0,0,0,0,0,0,0,0,0,0,0,  "lidt",0,0,0,0,0,0,0,0,0,0,0,0
               db "smsw",0,0,0,0,0,0,0,0,0,0,0,0,  "(bad)",0,0,0,0,0,0,0,0,0,0,0
               db "lmsw",0,0,0,0,0,0,0,0,0,0,0,0,  "invlpg",0,0,0,0,0,0,0,0,0,0
g7_mem_sizes:  db 0, 0, 0, 0, 16, 0xFF, 16, 8
; 0F 01 with a register form: the whole ModRM byte, then the name (16-byte slots)
g7_reg_names:  db 0xC8, "monitor", 0, 0,0,0,0,0,0,0
               db 0xC9, "mwait", 0, 0,0,0,0,0,0,0,0,0
               db 0xCA, "clac", 0, 0,0,0,0,0,0,0,0,0,0
               db 0xCB, "stac", 0, 0,0,0,0,0,0,0,0,0,0
               db 0xD0, "xgetbv", 0, 0,0,0,0,0,0,0,0
               db 0xD1, "xsetbv", 0, 0,0,0,0,0,0,0,0
               db 0xD5, "xend", 0, 0,0,0,0,0,0,0,0,0,0
               db 0xD6, "xtest", 0, 0,0,0,0,0,0,0,0,0
               db 0xEE, "rdpkru", 0, 0,0,0,0,0,0,0,0
               db 0xEF, "wrpkru", 0, 0,0,0,0,0,0,0,0
               db 0xF8, "swapgs", 0, 0,0,0,0,0,0,0,0
               db 0xF9, "rdtscp", 0, 0,0,0,0,0,0,0,0
               db 0
; 0F AE with a memory operand, and the register forms /5 /6 /7
gae_mem_names: db "fxsave",0,0,0,0,0,0,0,0,0,0,  "fxrstor",0,0,0,0,0,0,0,0,0
               db "ldmxcsr",0,0,0,0,0,0,0,0,0,  "stmxcsr",0,0,0,0,0,0,0,0,0
               db "xsave",0,0,0,0,0,0,0,0,0,0,0,  "xrstor",0,0,0,0,0,0,0,0,0,0
               db "xsaveopt",0,0,0,0,0,0,0,0,  "clflush",0,0,0,0,0,0,0,0,0
gae_mem_sizes: db 0, 0, 32, 32, 0, 0, 0, 8
gae_reg_names: db "lfence",0,0, "mfence",0,0, "sfence",0,0

%include "tools/disasm/x86_tables.inc"
