#!/usr/bin/env python3
"""
gen_mnemonic_names.py - regenerate error/mnemonic_names.inc

The x86-64 mnemonic table (backend/isa/amd64.s, mnc_tb_x64) stores only
FNV-1a hashes of the names, which is all the parser needs. The "did you
mean" hints (error/hints.s) need the names themselves, so this script
extracts every `mnc_ent "name", ...` line from the table and writes them
as a packed, NUL-separated string list, de-duplicated in table order.

Run it after adding or renaming mnemonics in backend/isa/amd64.s:

    python3 scripts/gen_mnemonic_names.py

`--check` exits non-zero if the committed file is out of date (for CI).
"""

import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "backend", "isa", "amd64.s")
DST = os.path.join(ROOT, "error", "mnemonic_names.inc")
PER_LINE = 8


def render() -> str:
    names, seen = [], set()
    with open(SRC, encoding="utf-8") as f:
        for line in f:
            m = re.match(r'\s*mnc_ent\s+"([^"]+)"', line)
            if m and m.group(1) not in seen:
                seen.add(m.group(1))
                names.append(m.group(1))
    if not names:
        sys.exit("gen_mnemonic_names: no mnc_ent lines found in " + SRC)

    out = [
        "; " + "=" * 76,
        "; GENERATED by scripts/gen_mnemonic_names.py from backend/isa/amd64.s.",
        "; Do not edit by hand - rerun the script after changing mnc_tb_x64.",
        "; " + "=" * 76,
        ";",
        "; x86-64 mnemonic names as a packed, NUL-separated list, used only for",
        "; \"did you mean\" hints (error/hints.s). %d unique names." % len(names),
        "",
        "mnemonic_names_x64:",
    ]
    for i in range(0, len(names), PER_LINE):
        chunk = names[i:i + PER_LINE]
        out.append("    db " + ", ".join('"%s", 0' % n for n in chunk))
    out.append("mnemonic_names_x64_end:")
    return "\n".join(out) + "\n"


def main() -> None:
    text = render()
    if "--check" in sys.argv:
        current = open(DST, encoding="utf-8").read() if os.path.exists(DST) else ""
        if current.replace("\r\n", "\n") != text:
            sys.exit("error/mnemonic_names.inc is out of date; run scripts/gen_mnemonic_names.py")
        return
    with open(DST, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


if __name__ == "__main__":
    main()
